package main

// The `docs` verb prints the whole command surface as one markdown document,
// with the EXACT page --help prints fenced under each heading — produced by
// the same renderer, so the reference and the binary are byte-identical by
// construction rather than by review discipline (cli-help.md §8).
//
// Three consumers, one file: the committed docs/cli-help.md (a suite test
// regenerates and byte-diffs it, so a stale reference fails the build), the
// website that serves it, and an agent or script that runs `docs` instead of
// scraping --help level by level.

import (
	"flag"
	"fmt"
	"io"
	"strings"
)

// referenceFile is the committed reference the build gate compares against.
const referenceFile = "docs/cli-help.md"

func runDocs(e *env, n *node, args []string) error {
	fs := flag.NewFlagSet(toolName+" "+pathOf(n), flag.ContinueOnError)
	handled, err := parseVerbFlags(e, n, fs, args)
	if handled || err != nil {
		return err
	}
	if err := rejectResiduals(n, fs); err != nil {
		return err
	}
	writeReference(e.stdout)
	return nil
}

// writeReference renders the document. It is a function of the tree alone, so
// the gate test can call it without running the binary.
func writeReference(w io.Writer) {
	fmt.Fprintf(w, "# `%s` command reference\n\n", toolName)
	fmt.Fprintf(w, "Generated by `%s docs`. Do not edit — regenerate with:\n\n", toolName)
	fmt.Fprintf(w, "```sh\ngo run ./cmd/%s docs > %s\n```\n\n", toolName, referenceFile)

	var emit func(n *node, depth int)
	emit = func(n *node, depth int) {
		heading := strings.Repeat("#", depth+2)
		title := toolName
		if n != root {
			title = toolName + " " + pathOf(n)
		}
		fmt.Fprintf(w, "%s `%s`\n\n%s\n\n```\n%s```\n\n", heading, title, n.summary, page(n))
		for _, c := range n.children {
			emit(c, depth+1)
		}
	}
	emit(root, 0)
}
