#!/bin/sh
# ============================ GENERATED REFERENCE COPY =====================
# DO NOT EDIT THIS FILE. Canonical source: the daemon repo's
# install/install.sh.in (clawee-git/daemon). tools/release.sh renders THAT
# template at cut time (sed s/__CLAWEED_VERSION__/<stamp>/) — the release zip
# NEVER ships this copy; it exists only so repo-local shellcheck + reviews
# audit the same code that ships. Refresh whenever the canonical template
# changes: re-render it with __CLAWEED_VERSION__ -> (rendered-at-build) and
# keep this header block. Last synced: 2026-07-29 (daemon @ c5ad76d).
# ===========================================================================
# claweed installer — LOCAL-SOURCE variant (POSIX sh, macOS + Linux).
#
# This is the Phase-B `claweed` release-component installer (it installs the
# claweed PTY daemon + the setuid clawee-spawn helper, and cross-installs the
# burrowee-gateway dependency), in a variant that sources clawee's OWN binaries
# from this staged directory instead of a signed GitHub release fronted by
# release.clawee.org. It is generated + staged by install/build-local.sh; the
# claweed + clawee-spawn binaries sit alongside this script.
#
# SUDO-MINIMAL model. Run this AS THE USER — do NOT prefix it with sudo. Almost
# everything (the claweed binary, the data-dir, the gateway dependency, the
# doctor tail) installs with NO privilege. The script escalates with `sudo` for
# exactly TWO steps:
#   - Tier S: the setuid-root spawn helper + its root-owned allowlist.
#   - the SYSTEM boot unit (/Library/LaunchDaemons on macOS, /etc/systemd/system
#     on Linux) — written/loaded via sudo ONLY when its content changed or it
#     isn't loaded. The unit is system-level so claweed starts at boot without
#     a GUI login, but it RUNS AS YOU (UserName/User=); binaries, data-dir and
#     config stay per-user.
# If sudo isn't available, the rest of the install still completes and the
# exact sudo block(s) are printed for you to run by hand.
#
# Usage (from the staged dir):
#   sh ./install.sh                 # interactive: prompts before the boot step
#   sh ./install.sh --yes           # unattended: assume-yes; also loads the boot unit
#   sh ./install.sh uninstall       # remove claweed + the setuid helper (keeps data)
#   sh ./install.sh uninstall --purge   # also remove ~/.clawee/data (tenant trust keys!)
#
# Env:
#   CLAWEE_PREFIX           install root for the USER-tier claweed binary
#                           (default: ~/.local/bin; user-writable, no sudo)
#   CLAWEE_REGISTER_SOCKET  burrowee-gateway register socket the daemon dials
#                           (default: auto-detected from the running gateway)
#   CLAWEE_DATA_DIR         claweed --data-dir (default: ~/.clawee/data)
#   CLAWEE_FORCE_SERVICE_OVERRIDE=1
#                           consent to replacing a system boot unit that belongs
#                           to a DIFFERENT user (the system slot is single — it
#                           is normally owned by whoever installed first)
#
# Only clawee's own channel is replaced by this local source; the burrowee
# dependency still installs from burrowee's PUBLIC channel
# (release.burrowee.com/gateway/install.sh).
set -eu

# ---- knobs --------------------------------------------------------------
# Tier U (no sudo): the claweed binary lands in a USER-writable prefix.
PREFIX="${CLAWEE_PREFIX:-$HOME/.local/bin}"
CLAWEED_BIN="$PREFIX/claweed"

# Tier S (sudo only): the setuid spawn helper + allowlist MUST live in a
# root-owned, NON-user-writable dir. A user-writable setuid-root binary is a
# trivial local-root escalation (anyone overwrites it, then triggers it as
# root) — so these paths are HARDCODED to /usr/local and are NEVER derived from
# CLAWEE_PREFIX. Do not move them under ~/.local/bin or any user-writable root.
SPAWN_DIR="/usr/local/bin"
SPAWN_HELPER="$SPAWN_DIR/clawee-spawn"
ETC_DIR="/usr/local/etc/clawee"
ALLOW_FILE="$ETC_DIR/spawn-allow"
# The operator opt-in that lets a SYSTEM account (root or a service uid) host
# tenant sessions. The spawn helper refuses to fork a child as any uid below the
# platform floor unless that uid is listed here, so a host administered entirely
# as root installs fine and then fails at the FIRST session without it. Written
# only when the installing user is itself below the floor — an ordinary user
# install never creates it, and the refusal stays in force everywhere else.
SYS_UID_FILE="$ETC_DIR/spawn-allow-system-uids"
# Legacy: the old all-sudo installer put claweed here. We clean it up below.
LEGACY_CLAWEED_BIN="/usr/local/bin/claweed"

LABEL="org.clawee.claweed"
VERSION="(rendered-at-build)"

# System boot-unit locations. The CLAWEE_*_DIR overrides are TEST SEAMS for the
# sandboxed installer harness (install_test.sh) — never set them in production.
LAUNCHD_DIR="${CLAWEE_LAUNCHD_DIR:-/Library/LaunchDaemons}"
SYSTEMD_DIR="${CLAWEE_SYSTEMD_DIR:-/etc/systemd/system}"

# Minimum burrowee-gateway version this claweed expects (the register-link
# contract floor). Empty = accept any installed gateway; only install when none.
GATEWAY_FLOOR=""

# ---- helpers ------------------------------------------------------------
fail() { printf '\n  \xe2\x9c\x97 %s\n\n' "$*" >&2; exit 1; }
info() { printf '  \xe2\x86\x92 %s\n' "$*"; }
ok()   { printf '  \xe2\x9c\x93 %s\n' "$*"; }
warn() { printf '  ! %s\n' "$*" >&2; }

# sq VALUE — emit VALUE safely single-quoted for embedding in GENERATED shell
# (the root finisher). It wraps the value in single quotes and replaces every
# embedded single quote with the '\'' escape sequence, so a value containing a
# quote (or any metacharacter) can never break out of the quoting and inject
# commands into the script that later runs under `sudo sh` (M4). Use it for EVERY
# baked path/value in the finisher heredoc. Example: sq "a'b" -> 'a'\''b'.
sq() {
    printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

# tilde_path PATH — render an absolute path for the printed copy-paste blocks
# with a leading $HOME rewritten to a literal ~, so the commands carry no
# machine-specific home and each operator's shell re-expands ~ to THEIR own home.
# The ~ is emitted OUTSIDE the quotes (tilde expansion never happens inside
# quotes; POSIX exempts the expanded home from field splitting, so a space in
# $HOME is still safe) while the remainder is routed through sq() — this
# script's quoting discipline — so even an embedded single quote survives the
# operator's paste intact. Paths outside $HOME are sq-quoted whole.
tilde_path() {
    case "$1" in
        "$HOME"/*) printf '~/%s' "$(sq "${1#"$HOME"/}")" ;;
        "$HOME")   printf '~' ;;
        *)         sq "$1" ;;
    esac
}

# ---- argument parse -----------------------------------------------------
# install.sh                 -> install (default)
# install.sh uninstall [...]  -> uninstall mode
# --yes/-y                   -> assume-yes (install: load boot unit unattended)
# --purge                    -> uninstall: also remove the data-dir
# -h/--help                  -> usage
MODE=install
ASSUME_YES=0
PURGE=0
# Auto-restart claweed after an in-place update (default ON). When the service is
# already running — e.g. `claweed update` invoked from inside a claweed-brokered
# session — the boot step (re)starts it on the new binary WITHOUT prompting, via
# the service manager so it survives this session being torn down. --no-restart /
# CLAWEE_NO_RESTART=1 opts out (restart by hand later).
NO_RESTART=0
[ "${CLAWEE_NO_RESTART:-0}" = 1 ] && NO_RESTART=1
# Update mode — set by `claweed update` (via CLAWEE_UPDATE_MODE env) or the flags:
#   dry    — print what would change (binary / spawn / boot-unit) + whether a
#            restart is required, then STOP (no changes).
#   apply  — print the plan, PROMPT, apply on yes; restart only if changed.
#   auto   — apply unattended (no prompt); restart only if changed.
#   force  — apply, REPLACING EVERYTHING even if identical; always restart.
# Empty = the normal interactive install (a fresh install / direct run).
UPDATE_MODE="${CLAWEE_UPDATE_MODE:-}"
usage() {
    cat <<EOF
claweed installer ($VERSION) — sudo-minimal

  sh ./install.sh [--yes] [--no-restart]   install (run AS THE USER, not sudo)
  sh ./install.sh --dry|--auto|--force     update: plan-only / apply / replace-all
  sh ./install.sh uninstall [--purge]      remove claweed + the setuid helper
  sh ./install.sh -h                       this help

  --dry         print the update plan (what would change + restart-required), no changes
  --auto        apply the update unattended; restart only if changed
  --force       reinstall everything (binary + spawn + boot-unit) + restart
  --yes         unattended install; install + load the boot unit without prompting
  --no-restart  apply, but don't restart a running claweed afterward
  --purge       uninstall only: also delete ~/.clawee/data (TENANT TRUST KEYS)

  The boot unit installs SYSTEM-level (/Library/LaunchDaemons on macOS,
  /etc/systemd/system on Linux) so claweed starts at boot with nobody logged
  in; it runs AS YOU. sudo is used only when the unit changed or isn't loaded.
  One system unit per host: CLAWEE_FORCE_SERVICE_OVERRIDE=1 consents to taking
  over another user's unit.
EOF
}
# Consume an optional leading subcommand (install|uninstall), then flags.
case "${1:-}" in
    uninstall|--uninstall) MODE=uninstall; shift ;;
    install) MODE=install; shift ;;
esac
for arg in "$@"; do
    case "$arg" in
        --yes|-y)     ASSUME_YES=1 ;;
        --no-restart) NO_RESTART=1 ;;
        --dry)        UPDATE_MODE=dry ;;
        --auto)       UPDATE_MODE=auto ;;
        --force)      UPDATE_MODE=force ;;
        --purge)      PURGE=1 ;;
        -h|--help)    usage; exit 0 ;;
        *) fail "unknown argument: $arg (try: sh ./install.sh -h)" ;;
    esac
done

# Derive the apply posture from the update mode (set by `claweed update`):
#   dry   — compute + print the plan, then exit (no changes).
#   apply — print the plan, PROMPT [y/N], apply on yes (the default).
#   auto  — apply unattended (assume-yes), no prompt.
#   force — apply, replacing everything even if identical.
# All apply modes restart ONLY when the binary or boot-unit changed (RESTART_NEEDED,
# computed in the plan) — except force, which always restarts. --no-restart skips it.
PLAN_ONLY=0
FORCE_REPLACE=0
case "$UPDATE_MODE" in
    dry)   PLAN_ONLY=1 ;;
    apply) ;;                              # prompts (ASSUME_YES stays 0)
    auto)  ASSUME_YES=1 ;;
    force) ASSUME_YES=1; FORCE_REPLACE=1 ;;
    "")    ;;  # interactive fresh install / direct run
    *)     fail "invalid CLAWEE_UPDATE_MODE: $UPDATE_MODE (dry|apply|auto|force)" ;;
esac

# version_of <cmd> [args…] — the first version-shaped token from that command's
# `--version` output, or "" if it prints none / isn't installed.
#
# `--version` output is HUMAN text, not a protocol, and every tool in this
# product shapes it differently:
#
#   clawee            clawee v0.1.101.2026.07.29.04e3b4cf
#   claweed           claweed v0.1.41.2026.07.29.d186508b (installed; running)
#   burrowee-gateway  burrowee-gateway v0.1.102…  (installed binary)
#                     running daemon:  v0.1.102…  ✓ up to date
#   burrowee-cli      a THREE-line "versions" block
#
# Parsing by field position therefore breaks the moment a tool adds a line or a
# suffix, and both callers below were broken by exactly that: `awk '{print $NF}'`
# on claweed returned "running)" (the trailing word of its suffix), and
# `awk '{print $2}'` on burrowee-gateway returned a TWO-line string, since awk
# prints the field for EVERY line. Matching the version SHAPE survives all four
# formats and any future reshuffle. Pipeline status is `head`'s (always 0), so a
# no-match cannot trip `set -e`; a missing binary yields "" rather than failing.
version_of() {
    "$@" --version 2>/dev/null |
        grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+[^[:space:]]*' | head -n1
}

# semver_lt A B — exit 0 iff version A is strictly older than B. Portable
# (no GNU `sort -V`): strips a leading 'v', splits on '.', compares fields
# numerically left-to-right, missing fields treated as 0. Non-numeric/garbage
# fields compare as 0.
semver_lt() {
    awk -v a="$1" -v b="$2" '
        function norm(s,   t) { sub(/^v/, "", s); return s }
        BEGIN {
            na = split(norm(a), x, ".")
            nb = split(norm(b), y, ".")
            n = (na > nb) ? na : nb
            for (i = 1; i <= n; i++) {
                xi = (i <= na) ? x[i] + 0 : 0
                yi = (i <= nb) ? y[i] + 0 : 0
                if (xi < yi) { exit 0 }
                if (xi > yi) { exit 1 }
            }
            exit 1   # equal -> not strictly less
        }'
}

# confirm PROMPT — returns 0 on yes. --yes makes it unconditional.
confirm() {
    [ "$ASSUME_YES" -eq 1 ] && return 0
    [ -r /dev/tty ] || { warn "no tty for prompt; re-run with --yes to proceed unattended"; return 1; }
    printf '  %s [y/N] ' "$1" >/dev/tty
    ans=''
    IFS= read -r ans </dev/tty || ans=''
    case "$ans" in y|Y|yes|YES) return 0 ;; *) return 1 ;; esac
}

# ---- identity + data-dir ------------------------------------------------
# This script runs AS THE INVOKING USER (no leading sudo), so id/$HOME are the
# real human's. The spawn allowlist trusts THIS uid — it's the uid claweed runs
# as (the SYSTEM boot unit's UserName/User= names this user too). The data-dir
# is this user's ~/.clawee/data.
USER_UID="$(id -u)"
USER_NAME="$(id -un)"
USER_GROUP="$(id -gn)"
DATA_DIR="${CLAWEE_DATA_DIR:-$HOME/.clawee/data}"

# ---- platform detection -------------------------------------------------
case "$(uname -s)" in
    Darwin) OS=darwin ;;
    Linux)  OS=linux ;;
    *)      fail "unsupported OS: $(uname -s) (claweed ships darwin + linux only)" ;;
esac
case "$(uname -m)" in
    arm64|aarch64) ARCH=arm64 ;;
    x86_64|amd64)  ARCH=amd64 ;;
    *)             fail "unsupported arch: $(uname -m)" ;;
esac
KIND=$( [ "$OS" = darwin ] && echo launchd || echo systemd )

# ---- system-account tenant (H3 floor) ------------------------------------
# Mirrors internal/spawn_helper minTenantUID: 1000 on linux (/etc/login.defs
# UID_MIN), 500 on darwin. When the installing user sits BELOW the floor — a box
# administered entirely as root is the common case — the spawn helper will
# refuse to fork sessions as that account unless the operator opts the uid in.
# The installer knows this at install time, so it writes the opt-in as part of
# the same privileged step that writes the caller allowlist, instead of leaving
# the operator to discover it at the first failed session.
MIN_TENANT_UID=$( [ "$OS" = darwin ] && echo 500 || echo 1000 )
NEEDS_SYS_UID=0
[ "$USER_UID" -lt "$MIN_TENANT_UID" ] && NEEDS_SYS_UID=1

# resolve the directory holding this script (the staged dir with the binaries).
SELF_DIR="$(cd "$(dirname "$0")" && pwd)"

# ---- system boot-unit helpers (shared by install + uninstall) ------------
# The boot unit is SYSTEM-level: /Library/LaunchDaemons (macOS) or
# /etc/systemd/system (Linux), running AS THE INVOKING USER — so claweed starts
# at boot with nobody logged in. Writing/loading it needs root.

# unit_path_for echoes the system boot-unit path for the current OS.
unit_path_for() {
    if [ "$OS" = darwin ]; then echo "$LAUNCHD_DIR/$LABEL.plist"
    else echo "$SYSTEMD_DIR/claweed.service"; fi
}

# root_posture — decide ONCE how privileged commands run: "direct" (already
# root), "sudo" (passwordless), "sudo_tty" (interactive password prompt on
# /dev/tty — works under `curl … | sh` too), or "none" (defer to a printed
# block). Cached in ROOT_HOW.
ROOT_HOW=""
root_posture() {
    [ -n "$ROOT_HOW" ] && return 0
    if [ "$USER_UID" -eq 0 ]; then ROOT_HOW=direct
    elif sudo -n true 2>/dev/null; then ROOT_HOW=sudo
    elif [ -r /dev/tty ]; then ROOT_HOW=sudo_tty
    else ROOT_HOW=none; fi
}

# run_root CMD ARGS… — run a privileged command per root_posture. Returns 1
# WITHOUT running anything when no sudo path exists (the caller defers).
run_root() {
    root_posture
    case "$ROOT_HOW" in
        direct)        "$@" ;;
        sudo|sudo_tty) sudo "$@" ;;
        none)          return 1 ;;
    esac
}

# unit_owner FILE — extract the run-as user recorded in a system unit (the
# plist <key>UserName</key> value / the systemd User= line); empty when the
# file is absent or carries no owner. Mirrors print-boot-unit's rendering so
# the single system slot's ownership is unambiguous.
unit_owner() {
    [ -f "$1" ] || return 0
    if [ "$OS" = darwin ]; then
        sed -n 's/.*<key>UserName<\/key><string>\([^<]*\)<\/string>.*/\1/p' "$1" | head -n 1
    else
        sed -n 's/^User=//p' "$1" | head -n 1
    fi
}

# remove_legacy_user_unit — best-effort teardown of the pre-system-level
# PER-USER boot unit (the gui-domain LaunchAgent / systemd --user unit) this
# installer used to write. Idempotent, no sudo (everything is user-owned);
# used by both the install migration and uninstall.
remove_legacy_user_unit() {
    if [ "$OS" = darwin ]; then
        legacy_unit="$HOME/Library/LaunchAgents/$LABEL.plist"
        launchctl bootout "gui/$USER_UID/$LABEL" 2>/dev/null || true
        launchctl bootout "user/$USER_UID/$LABEL" 2>/dev/null || true
        if [ -f "$legacy_unit" ]; then
            rm -f "$legacy_unit" && ok "removed legacy LaunchAgent $legacy_unit"
        fi
    else
        legacy_unit="$HOME/.config/systemd/user/claweed.service"
        legacy_present=0
        [ -f "$legacy_unit" ] && legacy_present=1
        systemctl --user is-enabled claweed.service >/dev/null 2>&1 && legacy_present=1
        if [ "$legacy_present" -eq 1 ]; then
            systemctl --user disable --now claweed.service 2>/dev/null || true
            rm -f "$legacy_unit" 2>/dev/null || true
            systemctl --user daemon-reload 2>/dev/null || true
            ok "removed legacy systemd user unit"
        fi
    fi
}

# system_unit_loaded — is the claweed system unit known to the system service
# manager right now? (Both probes are readable without root.)
system_unit_loaded() {
    if [ "$OS" = darwin ]; then launchctl print "system/$LABEL" >/dev/null 2>&1
    else systemctl is-active --quiet claweed.service 2>/dev/null; fi
}

# =========================================================================
# UNINSTALL MODE
# =========================================================================
if [ "$MODE" = uninstall ]; then
    printf '\n  claweed uninstaller  %s  (%s/%s)\n\n' "$VERSION" "$OS" "$ARCH"

    # ---- system boot unit (sudo) + legacy per-user units (no sudo) --------
    UNIT_PATH="$(unit_path_for)"
    UNIT_MANUAL=0
    if [ -f "$UNIT_PATH" ] || system_unit_loaded; then
        if [ "$OS" = darwin ]; then
            if run_root sh -c "launchctl bootout 'system/$LABEL' 2>/dev/null; rm -f '$UNIT_PATH'"; then
                ok "unloaded + removed system unit $UNIT_PATH"
            else
                UNIT_MANUAL=1
            fi
        else
            if run_root sh -c "systemctl disable --now claweed.service 2>/dev/null; rm -f '$UNIT_PATH'; systemctl daemon-reload 2>/dev/null || true"; then
                ok "disabled + removed system unit $UNIT_PATH"
            else
                UNIT_MANUAL=1
            fi
        fi
    else
        info "no system boot unit at $UNIT_PATH — skipped"
    fi
    # Legacy per-user units from pre-system-level installs (user-owned, no sudo).
    remove_legacy_user_unit

    if [ -f "$CLAWEED_BIN" ]; then
        rm -f "$CLAWEED_BIN" && ok "removed $CLAWEED_BIN"
    else
        info "no claweed binary at $CLAWEED_BIN — skipped"
    fi

    CLAWEED_UPDATER_BIN="$PREFIX/claweed-updater"
    if [ -f "$CLAWEED_UPDATER_BIN" ]; then
        rm -f "$CLAWEED_UPDATER_BIN" && ok "removed $CLAWEED_UPDATER_BIN"
    else
        info "no claweed-updater binary at $CLAWEED_UPDATER_BIN — skipped"
    fi

    # Staged setuid source + generated finisher left by an install that deferred
    # the Tier-S step (the live setuid copy in /usr/local is removed in Tier S
    # below).
    if [ -f "$HOME/.clawee/clawee-spawn" ]; then
        rm -f "$HOME/.clawee/clawee-spawn" && ok "removed staged $HOME/.clawee/clawee-spawn"
    fi
    if [ -f "$HOME/.clawee/clawee-spawn-setup.sh" ]; then
        rm -f "$HOME/.clawee/clawee-spawn-setup.sh" && ok "removed staged $HOME/.clawee/clawee-spawn-setup.sh"
    fi

    if [ "$PURGE" -eq 1 ]; then
        if [ -d "$DATA_DIR" ]; then
            warn "--purge: removing the data-dir $DATA_DIR (this deletes tenant trust keys; enrolled devices must re-enroll)"
            rm -rf "$DATA_DIR" && ok "removed data-dir $DATA_DIR"
        else
            info "no data-dir at $DATA_DIR — skipped"
        fi
    else
        if [ -d "$DATA_DIR" ]; then
            info "kept data-dir $DATA_DIR (holds tenant trust keys; pass --purge to remove)"
        fi
    fi

    # print_unit_manual_block — the copy-paste commands to remove the system
    # boot unit by hand (printed when run_root had no sudo path).
    print_unit_manual_block() {
        cat >&2 <<EOF

  ! the system boot unit needs root to remove — do it by hand:

EOF
        if [ "$OS" = darwin ]; then
            printf "      sudo launchctl bootout 'system/%s' 2>/dev/null || true\n" "$LABEL" >&2
            printf "      sudo rm -f '%s'\n" "$UNIT_PATH" >&2
        else
            printf '      sudo systemctl disable --now claweed.service\n' >&2
            printf "      sudo rm -f '%s'\n" "$UNIT_PATH" >&2
            printf '      sudo systemctl daemon-reload\n' >&2
        fi
    }

    # ---- Tier S (sudo, only if anything root-owned is present) -----------
    NEED_TIER_S=0
    [ -e "$SPAWN_HELPER" ] && NEED_TIER_S=1
    [ -e "$ALLOW_FILE" ] && NEED_TIER_S=1
    [ -e "$SYS_UID_FILE" ] && NEED_TIER_S=1
    [ -e "$LEGACY_CLAWEED_BIN" ] && NEED_TIER_S=1
    if [ "$NEED_TIER_S" -eq 0 ]; then
        if [ "$UNIT_MANUAL" -eq 1 ]; then
            print_unit_manual_block
            printf '\n' >&2
            warn "claweed uninstalled (user tier); the system boot unit was left for the manual block above"
            exit 4
        fi
        info "no root-owned spawn helper / allowlist present — nothing for sudo to remove"
        printf '\n  \xe2\x9c\x93 claweed uninstalled (local-source, %s)\n\n' "$VERSION"
        exit 0
    fi

    SUDO=""
    if [ "$USER_UID" -eq 0 ]; then
        SUDO=""
    elif sudo -n true 2>/dev/null; then
        SUDO="sudo"
    else
        [ "$UNIT_MANUAL" -eq 1 ] && print_unit_manual_block
        cat >&2 <<EOF

  ! the setuid spawn helper + allowlist are root-owned — passwordless sudo is
    not available, so remove them by hand:

      sudo rm -f '$SPAWN_HELPER' '$ALLOW_FILE' '$SYS_UID_FILE'
      sudo rmdir '$ETC_DIR' 2>/dev/null || true
EOF
        if [ -e "$LEGACY_CLAWEED_BIN" ]; then
            printf "      sudo rm -f '%s'   # legacy all-sudo install\n" "$LEGACY_CLAWEED_BIN" >&2
        fi
        printf '\n' >&2
        warn "claweed uninstalled (user tier); the root-owned spawn tier was left for the manual block above"
        exit 4
    fi

    if [ -e "$SPAWN_HELPER" ]; then
        $SUDO rm -f "$SPAWN_HELPER" && ok "removed $SPAWN_HELPER"
    fi
    if [ -e "$ALLOW_FILE" ]; then
        $SUDO rm -f "$ALLOW_FILE" && ok "removed $ALLOW_FILE"
    fi
    if [ -e "$SYS_UID_FILE" ]; then
        $SUDO rm -f "$SYS_UID_FILE" && ok "removed $SYS_UID_FILE"
    fi
    # rmdir only when empty — never recursive (it's a shared /usr/local tree).
    if [ -d "$ETC_DIR" ] && $SUDO rmdir "$ETC_DIR" 2>/dev/null; then
        ok "removed empty $ETC_DIR"
    fi
    if [ -e "$LEGACY_CLAWEED_BIN" ]; then
        $SUDO rm -f "$LEGACY_CLAWEED_BIN" && ok "removed legacy $LEGACY_CLAWEED_BIN"
    fi

    printf '\n  \xe2\x9c\x93 claweed uninstalled (local-source, %s)\n\n' "$VERSION"
    exit 0
fi

# =========================================================================
# INSTALL MODE
# =========================================================================
printf '\n  claweed installer (local-source)  %s  (%s/%s)\n\n' "$VERSION" "$OS" "$ARCH"

# Refuse a blanket-sudo run: under sudo $HOME/id are root's, so the whole
# user tier would land in root's home + trust root's uid — exactly the old
# broken model this restructure removes. Tier S escalates per-command instead.
if [ "$USER_UID" -eq 0 ] && [ -n "${SUDO_USER:-}" ]; then
    fail "don't run this under sudo — run it AS YOUR USER (the script escalates with sudo only for the spawn helper). Re-run: sh ./install.sh"
fi

# ---- preflight: staged binaries present ---------------------------------
for b in claweed clawee-spawn claweed-updater; do
    [ -f "$SELF_DIR/$b" ] || fail "missing $b in $SELF_DIR — re-run build-local.sh to stage the binaries"
done

# ---- register socket (detect early; unprivileged) -----------------------
# Resolve the burrowee-gateway register.sock the daemon dials: explicit env
# wins; else detect from open unix sockets. Done up front so the PLAN below can
# render the boot unit to compare, and the Tier-S manual hint can quote the real
# path. lsof can return several matches (multiple gateways) — auto-use a UNIQUE
# match; on >1 prefer THIS user's home gateway when present, else leave empty.
REGISTER_SOCKET="${CLAWEE_REGISTER_SOCKET:-}"
if [ -z "$REGISTER_SOCKET" ] && command -v lsof >/dev/null 2>&1; then
    # Use lsof's field output (-F n) so the socket NAME is on its own line (n-prefixed),
    # not the whitespace-split last column of the human table — a path containing a
    # space (e.g. a $HOME with a space) would otherwise be truncated by `awk $NF`.
    # The name field is NOT the bare path on every lsof: Linux (4.93+) appends the
    # socket type — "n/path/register.sock type=STREAM" — while macOS (4.91) emits
    # "n/path/register.sock". Strip that trailing " type=<KIND>" before matching, or
    # the anchored grep below silently finds nothing on Linux and the boot unit is
    # never rendered. Unnamed sockets ("ntype=DGRAM") have no leading space, so they
    # survive the strip unchanged and are dropped by the grep.
    socket_matches="$(lsof -U -F n 2>/dev/null \
        | sed -n 's/^n//p' \
        | sed 's/ type=[^ ]*$//' \
        | grep '/register\.sock$' \
        | sort -u)"
    match_count="$(printf '%s' "$socket_matches" | grep -c . || true)"
    if [ "$match_count" -eq 1 ]; then
        REGISTER_SOCKET="$socket_matches"
    elif [ "$match_count" -gt 1 ]; then
        # Several gateways' sockets are open (e.g. a CI/bare gateway under /tmp
        # alongside the real one). Prefer THIS user's canonical home gateway when
        # it is among the matches; only bail when it isn't.
        home_sock="$HOME/.burrowee/gateway/sockets/register.sock"
        if printf '%s\n' "$socket_matches" | grep -qxF "$home_sock"; then
            REGISTER_SOCKET="$home_sock"
            [ "$PLAN_ONLY" -eq 1 ] || info "multiple register sockets found — auto-picked the home gateway -> $home_sock"
        else
            warn "multiple burrowee-gateway register sockets found — cannot auto-pick:"
            printf '%s\n' "$socket_matches" | while IFS= read -r s; do warn "    $s"; done
            warn "set CLAWEE_REGISTER_SOCKET=<path> and re-run to choose one"
        fi
    fi
fi

# render_boot_unit BIN OUT — render the SYSTEM boot unit to OUT using BIN's
# print-boot-unit (BIN = the staged claweed during the plan, the installed one
# at apply time; the flags always name the INSTALLED paths). The unit runs as
# THIS user (--user/--group/--home) so only the boot slot is system-level.
render_boot_unit() {
    if [ "$OS" = darwin ]; then
        "$1" print-boot-unit --kind=launchd --claweed "$CLAWEED_BIN" \
            --data-dir "$DATA_DIR" --spawn-helper "$SPAWN_HELPER" \
            --register-socket "$REGISTER_SOCKET" \
            --user "$USER_NAME" --group "$USER_GROUP" --home "$HOME" \
            --log "$HOME/Library/Logs/claweed.log" >"$2" 2>/dev/null
    else
        "$1" print-boot-unit --kind=systemd --claweed "$CLAWEED_BIN" \
            --data-dir "$DATA_DIR" --spawn-helper "$SPAWN_HELPER" \
            --register-socket "$REGISTER_SOCKET" \
            --user "$USER_NAME" --group "$USER_GROUP" --home "$HOME" >"$2" 2>/dev/null
    fi
}

# spawn_unchanged / unit_unchanged are the idempotency checks shared by the PLAN
# and the apply steps: 0 = would change (or force), 1 = byte-identical.
spawn_unchanged() {
    [ "$FORCE_REPLACE" -eq 0 ] \
        && [ -f "$SPAWN_HELPER" ] && cmp -s "$SELF_DIR/clawee-spawn" "$SPAWN_HELPER" \
        && [ -f "$ALLOW_FILE" ] && grep -qx "$USER_UID" "$ALLOW_FILE" 2>/dev/null \
        && sys_uid_optin_ok
}
# sys_uid_optin_ok: 0 when the system-account opt-in is not needed, or is needed
# and already lists this uid. Folded into spawn_unchanged so a RE-INSTALL on a
# host that is missing it re-enters the privileged step and repairs it, rather
# than reporting "unchanged" and leaving sessions broken.
sys_uid_optin_ok() {
    [ "$NEEDS_SYS_UID" -eq 0 ] && return 0
    [ -f "$SYS_UID_FILE" ] && grep -qx "$USER_UID" "$SYS_UID_FILE" 2>/dev/null
}
unit_unchanged() {
    # Render the would-be unit with the STAGED claweed (the plan runs before the
    # binary is installed) and cmp against the installed SYSTEM unit (0644 —
    # readable without root). No socket / render failure / force ⇒ "changed".
    [ "$FORCE_REPLACE" -eq 0 ] && [ -n "$REGISTER_SOCKET" ] || return 1
    _up="$(unit_path_for)"; [ -f "$_up" ] || return 1
    _tmp="$(mktemp)"
    render_boot_unit "$SELF_DIR/claweed" "$_tmp" || { rm -f "$_tmp"; return 1; }
    _r=1; cmp -s "$_tmp" "$_up" || _r=0; rm -f "$_tmp"; [ "$_r" -eq 1 ]
}

# =========================================================================
# PLAN — what would change. Printed for every update mode (dry / apply / auto /
# force). dry STOPS here; apply PROMPTS before applying; auto/force assume-yes.
# =========================================================================
RESTART_NEEDED=0
if [ -n "$UPDATE_MODE" ]; then
    # NOT `awk '{print $NF}'`: claweed's --version ends "(installed; running)",
    # so the last field was the literal "running)". That can never equal
    # $VERSION, so bin_changed was ALWAYS 1 — every run planned a REPLACE and
    # set RESTART_NEEDED, bouncing a healthy daemon on an update that had
    # nothing to install, and printing "running) -> v0.1.41   REPLACE".
    installed_ver="$(version_of "$CLAWEED_BIN")"
    [ -n "$installed_ver" ] || installed_ver="(none)"
    bin_changed=1; [ "$FORCE_REPLACE" -eq 0 ] && [ "$installed_ver" = "$VERSION" ] && bin_changed=0
    spawn_unchanged && spawn_line="unchanged" || spawn_line="REPLACE"
    unit_unchanged && unit_line="unchanged" || unit_line="REWRITE"
    [ "$bin_changed" -eq 1 ] && bin_line="$installed_ver -> $VERSION   REPLACE" || bin_line="$VERSION   unchanged"
    # A restart is needed only when the binary or the boot unit changes — replacing
    # the setuid spawn helper alone does NOT bounce claweed. force always restarts.
    if [ "$FORCE_REPLACE" -eq 1 ] || [ "$bin_changed" -eq 1 ] || [ "$unit_line" = "REWRITE" ]; then
        RESTART_NEEDED=1
    fi
    [ "$RESTART_NEEDED" -eq 1 ] && restart_line="required" || restart_line="not required"
    printf '\n  update plan (%s):\n' "$VERSION"
    printf '    claweed binary   %s\n' "$bin_line"
    printf '    clawee-spawn     %s\n' "$spawn_line"
    printf '    boot-unit        %s\n' "$unit_line"
    printf '    restart claweed  %s\n\n' "$restart_line"
    if [ "$PLAN_ONLY" -eq 1 ]; then
        info "plan only (--dry) — nothing changed. apply with --auto, or --force to replace everything."
        exit 0
    fi
    # apply mode prompts here; auto/force assume-yes (ASSUME_YES → confirm returns 0).
    confirm "apply this update?" || { info "update skipped."; exit 0; }
fi

# =========================================================================
# TIER U (no sudo): claweed -> $PREFIX (0755), as the invoking user.
# =========================================================================
info "installing claweed -> $PREFIX"
mkdir -p "$PREFIX" || fail "could not create $PREFIX (set CLAWEE_PREFIX to a writable dir)"
[ -w "$PREFIX" ] || fail "$PREFIX is not writable — set CLAWEE_PREFIX to a user-writable dir"
# Detect whether the claweed binary actually changes BEFORE overwriting it: a
# byte-identical binary keeps its macOS Full-Disk-Access grant, a changed one
# (new ad-hoc signature) needs a re-grant. Mirrors spawn_unchanged for the FDA
# block below. Set under set -eu via the &&-list exemption (like SPAWN_SAME).
CLAWEED_SAME=0
[ -f "$CLAWEED_BIN" ] && cmp -s "$SELF_DIR/claweed" "$CLAWEED_BIN" && CLAWEED_SAME=1
install -m 0755 "$SELF_DIR/claweed" "$CLAWEED_BIN"
[ "$OS" = darwin ] && xattr -d com.apple.quarantine "$CLAWEED_BIN" 2>/dev/null || true
ok "claweed installed: $($CLAWEED_BIN --version 2>/dev/null || echo claweed)"

# claweed-updater — one-shot update trigger; no service unit.
CLAWEED_UPDATER_BIN="$PREFIX/claweed-updater"
install -m 0755 "$SELF_DIR/claweed-updater" "$CLAWEED_UPDATER_BIN"
[ "$OS" = darwin ] && xattr -d com.apple.quarantine "$CLAWEED_UPDATER_BIN" 2>/dev/null || true
ok "claweed-updater installed: $CLAWEED_UPDATER_BIN"

# PATH hint: ~/.local/bin is frequently NOT on PATH.
if ! command -v claweed >/dev/null 2>&1; then
    warn "claweed is not on PATH yet — add $PREFIX to PATH:"
    warn "  export PATH=\"$PREFIX:\$PATH\"   # add to ~/.profile or your shell rc"
else
    case ":$PATH:" in
        *":$PREFIX:"*) ;;
        *) warn "$PREFIX is not on PATH — add: export PATH=\"$PREFIX:\$PATH\"" ;;
    esac
fi

# ---- data-dir (this user's ~/.clawee/data, 0700) — no sudo --------------
# Never clobber an existing data-dir — it holds tenant trust keys. Only create
# (0700) when absent; leave an existing one untouched.
if [ -d "$DATA_DIR" ]; then
    ok "data-dir exists -> $DATA_DIR (left untouched)"
else
    info "creating data-dir -> $DATA_DIR (0700)"
    install -d -m 700 "$DATA_DIR" || fail "could not create data-dir $DATA_DIR"
    ok "data-dir ready"
fi

# =========================================================================
# TIER S (sudo, ONLY this): setuid clawee-spawn + root-owned allowlist.
#
#   SECURITY INVARIANT: the setuid-root binary stays root-owned in a
#   NON-user-writable dir (/usr/local/bin), and the allowlist stays root-owned,
#   non-group/world-writable (0644). A user-writable setuid file would let any
#   local user overwrite it and run arbitrary code as root.
#
#   need_sudo posture: run the Tier-S commands with sudo if we already are root
#   or passwordless sudo works; otherwise PRINT the exact Tier-S block (the rest
#   of the install is done — the spawn helper is the only remainder) and exit
#   non-zero so the operator knows to run it.
# =========================================================================
# Tier-S idempotency (the common `claweed update` case): when the installed setuid
# helper is byte-identical to the staged one AND the allowlist already trusts this
# uid (and we're not --force), the whole privileged tier is a no-op — skip it
# entirely (no sudo, no password prompt, no macOS Full-Disk-Access re-grant). The
# shared spawn_unchanged() reads the root-owned files unprivileged (4755 helper +
# 0644 allowlist are both world-readable) and honours FORCE_REPLACE.
SPAWN_SAME=0
spawn_unchanged && SPAWN_SAME=1

SPAWN_SKIPPED=0
SUDO=""
if [ "$SPAWN_SAME" -eq 1 ]; then
    ok "clawee-spawn + allowlist unchanged -> $SPAWN_HELPER (skipped — no sudo)"
elif [ "$USER_UID" -eq 0 ]; then
    SUDO=""
elif sudo -n true 2>/dev/null; then
    SUDO="sudo"                       # passwordless — run silently
elif [ -r /dev/tty ]; then
    # No passwordless sudo, but a terminal is attached: run the ONE privileged
    # step interactively. sudo reads the password from /dev/tty (not stdin), so
    # this works even under `curl … | sh` — the same /dev/tty the confirm()
    # prompt already uses. Only when there is NO tty (CI / fully unattended) do
    # we skip and leave the printed block + saved script for a later manual run.
    SUDO="sudo"
    info "the one privileged step (setuid clawee-spawn) needs sudo — you'll be prompted for your password"
else
    SPAWN_SKIPPED=1
fi

if [ "$SPAWN_SAME" -eq 1 ]; then
    : # spawn helper + allowlist already current — nothing to install (handled above)
elif [ "$SPAWN_SKIPPED" -eq 1 ]; then
    # No passwordless sudo, so the ONE privileged step (setuid clawee-spawn +
    # root-owned allowlist) can't run inline. Stage the setuid SOURCE to a
    # durable, user-owned path AND write the privileged step out as a small
    # script the operator runs once with `sudo sh`. Both live in $HOME/.clawee
    # (the user's own tree) so they survive this installer's temp dir being
    # cleaned up before the operator gets to them; a non-setuid copy there is
    # harmless (it refuses to run without setuid), and the script's
    # `install -m 4755 -o root` makes the privileged copy in the root-owned dir.
    #
    # The generated script bakes ABSOLUTE paths + the invoking uid: it runs as
    # root under sudo, where ~ / $HOME would resolve to root's home, not this
    # user's — so a literal ~ there would point at the wrong tree.
    CLAWEE_HOME="$HOME/.clawee"
    mkdir -p "$CLAWEE_HOME"
    chmod 0700 "$CLAWEE_HOME" 2>/dev/null || true   # holds a soon-setuid binary + a root-run script

    STAGED_SPAWN="$CLAWEE_HOME/clawee-spawn"
    cp "$SELF_DIR/clawee-spawn" "$STAGED_SPAWN"
    chmod 0755 "$STAGED_SPAWN"
    [ "$OS" = darwin ] && xattr -d com.apple.quarantine "$STAGED_SPAWN" 2>/dev/null || true

    # Write the privileged finisher. Escaped \$(id -u) / \$0 stay live in the
    # generated file; every other value bakes its (absolute, root-safe) value now,
    # safely single-quoted via sq() so a path containing a single quote (e.g. a
    # $HOME with a ') can never break out of the quoting and inject commands into
    # the script that then runs under `sudo sh` (M4). Each sq'd value ALREADY
    # carries its surrounding single quotes, so the heredoc references them bare.
    SETUP_SCRIPT="$CLAWEE_HOME/clawee-spawn-setup.sh"
    Q_STAGED_SPAWN="$(sq "$STAGED_SPAWN")"
    Q_SPAWN_DIR="$(sq "$SPAWN_DIR")"
    Q_SPAWN_HELPER="$(sq "$SPAWN_HELPER")"
    Q_ETC_DIR="$(sq "$ETC_DIR")"
    Q_ALLOW_FILE="$(sq "$ALLOW_FILE")"
    Q_SYS_UID_FILE="$(sq "$SYS_UID_FILE")"
    Q_USER_UID="$(sq "$USER_UID")"
    {
        cat <<EOF
#!/bin/sh
# clawee-spawn privileged finisher — generated by the claweed installer.
# The user-tier install is done; this installs the ONE thing that needs root:
# the setuid-root clawee-spawn helper (into a root-owned, non-user-writable dir)
# and its root-owned allowlist. Run as root:  sudo sh <this file>
# Idempotent; safe to re-run. The installer's uninstall mode removes it.
set -eu
if [ "\$(id -u)" -ne 0 ]; then
    echo "clawee-spawn-setup: run me as root — e.g.  sudo sh \$0" >&2
    exit 1
fi
mkdir -p $Q_SPAWN_DIR
install -m 4755 -o root $Q_STAGED_SPAWN $Q_SPAWN_HELPER
mkdir -p $Q_ETC_DIR
printf '%s\n' $Q_USER_UID > $Q_ALLOW_FILE
chown root $Q_ALLOW_FILE
chmod 0644 $Q_ALLOW_FILE
EOF
        # System-account tenant: also write the opt-in that lets the helper fork
        # sessions as this below-the-floor uid. Appended to the SAME root script
        # so the operator runs one block, not two.
        if [ "$NEEDS_SYS_UID" -eq 1 ]; then
            cat <<EOF
# $USER_NAME (uid $USER_UID) is below the tenant uid floor ($MIN_TENANT_UID), so
# the setuid helper refuses to fork sessions as it unless opted in here. This
# widens the trust boundary on THIS host: a claweed compromise would reach
# $USER_NAME. Remove the line to revoke.
if ! grep -qx $Q_USER_UID $Q_SYS_UID_FILE 2>/dev/null; then
    printf '%s\n' $Q_USER_UID >> $Q_SYS_UID_FILE
fi
chown root $Q_SYS_UID_FILE
chmod 0644 $Q_SYS_UID_FILE
EOF
        fi
        if [ -e "$LEGACY_CLAWEED_BIN" ]; then
            printf 'rm -f %s   # legacy all-sudo install of claweed\n' "$(sq "$LEGACY_CLAWEED_BIN")"
        fi
        printf 'echo "  clawee-spawn installed setuid-root; allowlist authorizes uid %s"\n' "$USER_UID"
    } > "$SETUP_SCRIPT"
    chmod 0755 "$SETUP_SCRIPT"

    # Show the run + verify commands home-relative (~) so no machine-specific
    # path is printed; the operator's shell re-expands ~ to their own home, and
    # `sudo sh` then runs the script (which itself uses the baked absolute paths).
    SETUP_DISP="$(tilde_path "$SETUP_SCRIPT")"
    CLAWEED_BIN_DISP="$(tilde_path "$CLAWEED_BIN")"
    cat >&2 <<EOF

  ! Tier S (the ONLY privileged step) was skipped — no passwordless sudo.
    claweed is installed; one privileged step remains. I wrote it to a script —
    run it once as root, then verify as yourself:

      sudo sh $SETUP_DISP
      $CLAWEED_BIN_DISP status

EOF
else
    info "installing clawee-spawn setuid-root (4755) -> $SPAWN_HELPER"
    # $SPAWN_DIR (/usr/local/bin) may not exist on a fresh macOS (Apple-Silicon
    # Homebrew lives at /opt/homebrew); BSD install won't create it. Make it
    # root-owned to satisfy the Tier-S non-user-writable invariant.
    $SUDO mkdir -p "$SPAWN_DIR"
    $SUDO install -m 4755 -o root "$SELF_DIR/clawee-spawn" "$SPAWN_HELPER"
    [ "$OS" = darwin ] && $SUDO xattr -d com.apple.quarantine "$SPAWN_HELPER" 2>/dev/null || true
    ok "clawee-spawn installed setuid-root (root-owned, non-user-writable dir)"

    info "writing spawn allowlist (uid $USER_UID, user $USER_NAME) -> $ALLOW_FILE"
    $SUDO mkdir -p "$ETC_DIR"
    printf '%s\n' "$USER_UID" | $SUDO tee "$ALLOW_FILE" >/dev/null
    $SUDO chown root "$ALLOW_FILE"
    $SUDO chmod 0644 "$ALLOW_FILE"
    ok "allowlist written (root-owned, 0644)"

    if [ "$NEEDS_SYS_UID" -eq 1 ]; then
        info "permitting system account $USER_NAME (uid $USER_UID < $MIN_TENANT_UID) to host sessions -> $SYS_UID_FILE"
        if ! $SUDO grep -qx "$USER_UID" "$SYS_UID_FILE" 2>/dev/null; then
            # Append, never truncate: another system uid may already be opted in.
            printf '%s\n' "$USER_UID" | $SUDO tee -a "$SYS_UID_FILE" >/dev/null
        fi
        $SUDO chown root "$SYS_UID_FILE"
        $SUDO chmod 0644 "$SYS_UID_FILE"
        ok "system-account opt-in written (root-owned, 0644) — a claweed compromise here would reach $USER_NAME"
    fi

    # Legacy cleanup: the old all-sudo installer placed claweed in /usr/local/bin.
    # The user-tier binary now lives in $PREFIX, so a stale copy there shadows it
    # on PATH — offer to remove it (Tier S, sudo).
    if [ -e "$LEGACY_CLAWEED_BIN" ] && [ "$LEGACY_CLAWEED_BIN" != "$CLAWEED_BIN" ]; then
        if confirm "remove the legacy root-owned $LEGACY_CLAWEED_BIN (from the old all-sudo install)?"; then
            $SUDO rm -f "$LEGACY_CLAWEED_BIN" && ok "removed legacy $LEGACY_CLAWEED_BIN"
        else
            warn "kept $LEGACY_CLAWEED_BIN — it may shadow $CLAWEED_BIN on PATH; remove with: sudo rm -f '$LEGACY_CLAWEED_BIN'"
        fi
    fi
fi

# =========================================================================
# DEPENDENCY: burrowee-gateway (cross-channel, PUBLIC burrowee installer)
#   No sudo here — burrowee's own installer escalates as it needs to. Install
#   when missing or older than floor; never downgrades. This is the ONE step
#   that stays public in this variant.
# =========================================================================
dep_burrowee_gateway() {
    # NOT `awk '{print $2}'`: burrowee-gateway prints TWO lines, and awk emits
    # field 2 of each, so $have became "v0.1.102…\ndaemon:" — which the ok()
    # line splattered across the screen and semver_lt then compared against the
    # floor.
    have="$(version_of burrowee-gateway)"
    if [ -z "$have" ]; then
        info "burrowee-gateway not found — installing from burrowee's public channel"
    elif [ -n "$GATEWAY_FLOOR" ] && semver_lt "$have" "$GATEWAY_FLOOR"; then
        info "burrowee-gateway $have is older than floor $GATEWAY_FLOOR — upgrading"
    else
        ok "burrowee-gateway present ($have) — dependency satisfied"
        return 0
    fi
    if ! command -v curl >/dev/null 2>&1; then
        warn "curl not found — cannot install burrowee-gateway; install it manually:"
        warn "  curl -fsSL https://release.burrowee.com/gateway/install.sh | sh"
        return 0
    fi
    # Threat model for the curl|sh below (accepted, by design): this is the ONE
    # public cross-channel step. We pin transport with --proto '=https' --tlsv1.2
    # (no http downgrade, no SSLv3/TLS1.0/1.1), so the fetch is authenticated to
    # release.burrowee.com by its TLS cert. We deliberately do NOT minisign-verify
    # the fetched bootstrap here: the burrowee bootstrap is its OWN minisign
    # trust-anchor — it verifies the gateway payload it then downloads against
    # burrowee's release key. Re-verifying it from clawee's installer would only
    # duplicate (and couple us to) burrowee's signing keys. We fetch to a var and
    # pipe so a truncated/failed fetch never partially executes.
    bootstrap="$(curl -fsSL --proto '=https' --tlsv1.2 \
        https://release.burrowee.com/gateway/install.sh 2>/dev/null)" || {
        warn "cannot reach release.burrowee.com — skipping burrowee-gateway install"; return 0; }
    printf '%s' "$bootstrap" | sh || warn "burrowee-gateway install reported an error"
}
dep_burrowee_gateway

# =========================================================================
# BOOT UNIT (SYSTEM-level): render via `claweed print-boot-unit` and install to
#   /Library/LaunchDaemons (macOS) / /etc/systemd/system (Linux), so claweed
#   starts at boot with NOBODY logged in. The unit RUNS AS THIS USER
#   (UserName/User= + HOME) — only the boot slot is system-level; binaries,
#   data-dir and config stay per-user. Root is needed ONLY when the unit
#   content changed or the unit isn't loaded: a routine `claweed update`
#   (binary-only change) restarts via the supervisor when root is free
#   (already root / passwordless sudo), else by SIGTERM-ing the running
#   same-uid daemon — KeepAlive(PathState) / Restart=always respawn it on the
#   new binary. When root is needed but unavailable, the rendered unit is
#   staged and the exact sudo block printed (never half-installed).
# =========================================================================
BOOT_DEFERRED=0

# stage_boot_sudo_block — stage the rendered unit ($NEW_UNIT) to a durable
# user-owned path and print the exact sudo commands that finish the boot step.
stage_boot_sudo_block() {
    CLAWEE_HOME="$HOME/.clawee"
    mkdir -p "$CLAWEE_HOME"
    STAGED_UNIT="$CLAWEE_HOME/$(basename "$UNIT_PATH")"
    cp "$NEW_UNIT" "$STAGED_UNIT"
    STAGED_DISP="$(tilde_path "$STAGED_UNIT")"
    cat >&2 <<EOF

  ! the SYSTEM boot unit needs sudo, which is not available right now.
    I staged the rendered unit — finish the boot step by hand:

      sudo install -m 0644 $STAGED_DISP '$UNIT_PATH'
EOF
    if [ "$OS" = darwin ]; then
        printf "      sudo launchctl bootout 'system/%s' 2>/dev/null || true\n" "$LABEL" >&2
        printf "      sudo launchctl bootstrap system '%s'\n" "$UNIT_PATH" >&2
    else
        printf '      sudo systemctl daemon-reload\n' >&2
        printf '      sudo systemctl enable --now claweed.service\n' >&2
    fi
    printf '\n' >&2
    BOOT_DEFERRED=1
}

# supervisor_restart — restart the loaded system unit through the OS
# supervisor (needs root; run_root decides how).
supervisor_restart() {
    if [ "$OS" = darwin ]; then run_root launchctl kickstart -k "system/$LABEL" 2>/dev/null
    else run_root systemctl restart claweed.service 2>/dev/null; fi
}

# restart_claweed_no_sudo — SIGTERM the running same-uid claweed. It prefers
# the pid the daemon RECORDED at serve startup ($DATA_DIR/pid — the file name
# matches cmd/claweed's runningPidFile): with two genuinely matching processes
# (e.g. a stuck stale daemon) a pattern match can SIGTERM the wrong one and
# report success while the live daemon keeps running old code. A valid
# recorded pid is used EXCLUSIVELY — when its verification below fails, the
# recorded daemon is gone and pgrep would only reintroduce the wrong-pid risk.
# pgrep discovery remains solely the fallback for an OLDER claweed that
# recorded no pid. Either way the pid is signalled only after verifying its
# command really names our binary + serve (a recycled pid must never be
# signalled). The system unit's KeepAlive(PathState) / Restart=always respawns
# it on the (possibly just-swapped) binary.
restart_claweed_no_sudo() {
    _pid=""
    if [ -f "$DATA_DIR/pid" ]; then
        _pid="$(tr -d '[:space:]' < "$DATA_DIR/pid" 2>/dev/null)"
        case "$_pid" in ''|*[!0-9]*) _pid="" ;; esac   # garbage record -> treat as absent
    fi
    if [ -z "$_pid" ]; then
        command -v pgrep >/dev/null 2>&1 || return 1
        _pid="$(pgrep -u "$USER_UID" -f "$CLAWEED_BIN serve" 2>/dev/null | head -n 1)"
        [ -n "$_pid" ] || return 1
    fi
    case "$(ps -o args= -p "$_pid" 2>/dev/null)" in
        "$CLAWEED_BIN serve"*) ;;
        *) return 1 ;;
    esac
    kill -TERM "$_pid" 2>/dev/null
}

# restart_claweed — the restart chain: supervisor restart when root is free
# (already root / passwordless sudo — never a surprise password prompt for a
# mere restart), else the no-sudo SIGTERM fallback, else — with a tty — an
# interactive-sudo supervisor restart as the last resort.
restart_claweed() {
    root_posture
    if [ "$ROOT_HOW" = direct ] || [ "$ROOT_HOW" = sudo ]; then
        supervisor_restart && return 0
    fi
    restart_claweed_no_sudo && return 0
    [ "$ROOT_HOW" = sudo_tty ] && supervisor_restart
}

if [ -z "$REGISTER_SOCKET" ]; then
    warn "could not detect the burrowee-gateway register socket."
    warn "render the boot unit yourself once the gateway is running:"
    warn "  $CLAWEED_BIN print-boot-unit --kind=$KIND --claweed '$CLAWEED_BIN' \\"
    warn "    --data-dir '$DATA_DIR' --spawn-helper '$SPAWN_HELPER' --register-socket <path> \\"
    warn "    --user '$USER_NAME' --group '$USER_GROUP' --home '$HOME'"
else
    info "register socket: $REGISTER_SOCKET"
    UNIT_PATH="$(unit_path_for)"
    [ "$OS" = darwin ] && mkdir -p "$HOME/Library/Logs"

    # Cross-user single-slot guard: the system unit path is ONE slot per host,
    # normally owned by whoever installed first. Refuse a silent takeover of
    # another user's unit unless CLAWEE_FORCE_SERVICE_OVERRIDE=1 consents.
    existing_owner="$(unit_owner "$UNIT_PATH")"
    if [ -n "$existing_owner" ] && [ "$existing_owner" != "$USER_NAME" ] \
        && [ "${CLAWEE_FORCE_SERVICE_OVERRIDE:-0}" != 1 ]; then
        fail "the system unit $UNIT_PATH belongs to user '$existing_owner' (one claweed system service per host) — re-run with CLAWEE_FORCE_SERVICE_OVERRIDE=1 to take it over"
    fi

    # Render with the INSTALLED binary to a temp; the write below happens only
    # when the content actually changed (idempotent — a routine version bump
    # leaves the unit identical, so no root is needed, only a binary restart).
    NEW_UNIT="$(mktemp)"
    render_boot_unit "$CLAWEED_BIN" "$NEW_UNIT" \
        || { rm -f "$NEW_UNIT"; fail "print-boot-unit failed"; }
    unit_changed=1
    if [ "$FORCE_REPLACE" -eq 0 ] && [ -f "$UNIT_PATH" ] && cmp -s "$NEW_UNIT" "$UNIT_PATH"; then unit_changed=0; fi

    loaded=0
    system_unit_loaded && loaded=1

    # Legacy per-user unit migration (idempotent, no sudo — everything legacy
    # is user-owned). Booting out a legacy agent stops the OLD daemon; live
    # session holders survive (they own the PTYs) and the system daemon
    # re-adopts them once loaded.
    remove_legacy_user_unit

    if [ "$unit_changed" -eq 0 ] && [ "$loaded" -eq 1 ]; then
        ok "system unit unchanged + loaded -> $UNIT_PATH"
        restart_hint=$( [ "$OS" = darwin ] \
            && echo "sudo launchctl kickstart -k system/$LABEL" \
            || echo "sudo systemctl restart claweed.service" )
        if [ "$NO_RESTART" -eq 1 ]; then
            info "auto-restart off (--no-restart) — restart later: $restart_hint"
        elif [ -n "$UPDATE_MODE" ] && [ "$RESTART_NEEDED" -eq 0 ]; then
            ok "claweed unchanged (binary + boot-unit) — no restart needed"
        elif restart_claweed; then
            ok "claweed restarting on the new build (system service)"
        else
            warn "could not restart claweed — restart it later: $restart_hint"
        fi
    else
        # The unit file and/or its load state needs root. A fresh interactive
        # install still asks first (--yes / update modes skip the prompt).
        boot_consented=1
        if [ "$loaded" -eq 0 ] && [ -z "$UPDATE_MODE" ]; then
            confirm "install + load the system boot unit now (needs sudo)?" || boot_consented=0
        fi
        root_posture
        if [ "$boot_consented" -eq 0 ] || [ "$ROOT_HOW" = none ]; then
            stage_boot_sudo_block
        else
            wrote_ok=1
            if [ "$unit_changed" -eq 1 ]; then
                if run_root install -m 0644 "$NEW_UNIT" "$UNIT_PATH"; then
                    ok "wrote system unit $UNIT_PATH"
                else
                    warn "could not write $UNIT_PATH (sudo failed)"
                    stage_boot_sudo_block
                    wrote_ok=0
                fi
            else
                ok "system unit unchanged -> $UNIT_PATH (kept)"
            fi
            if [ "$wrote_ok" -eq 1 ]; then
                if [ "$NO_RESTART" -eq 1 ] && [ "$loaded" -eq 1 ]; then
                    # The changed unit is on disk; reloading it would bounce the
                    # running daemon, which --no-restart opts out of.
                    info "auto-restart off (--no-restart) — the changed unit applies on the next reload/reboot"
                elif [ "$OS" = darwin ]; then
                    # bootout+bootstrap in ONE root shell: it both (re)loads the
                    # changed unit and restarts the daemon on the new binary.
                    if run_root sh -c "launchctl bootout 'system/$LABEL' 2>/dev/null; launchctl bootstrap system '$UNIT_PATH'"; then
                        ok "system unit loaded (launchd system domain)"
                    else
                        warn "could not load the system unit — load it manually:"
                        warn "  sudo launchctl bootstrap system '$UNIT_PATH'"
                    fi
                else
                    if run_root sh -c "systemctl daemon-reload; systemctl enable claweed.service >/dev/null 2>&1 || true; systemctl restart claweed.service"; then
                        ok "system unit enabled + started (systemd system)"
                    else
                        warn "could not start the system unit — start it manually:"
                        warn "  sudo systemctl enable --now claweed.service"
                    fi
                fi
            fi
        fi
    fi
    rm -f "$NEW_UNIT"
fi

# =========================================================================
# DOCTOR (informational): run the deployment diagnosis with the same paths the
#   boot unit uses. Runs AS THIS USER directly — the whole script is the user,
#   so no `sudo -u` is needed: doctor's checks are user-relative (the allowlist
#   trusts this uid, the LaunchAgent lives in this user's gui/<uid> domain, the
#   setuid helper accepts only this allowlisted caller). `claweed doctor` needs
#   (--register-socket|--socket), so skip when neither is known. Older binaries
#   lack the verb — detect via the usage text so a build without it never errors.
# =========================================================================
if ! "$CLAWEED_BIN" 2>&1 | grep -q 'doctor'; then
    info "claweed doctor not available in this build — skipping (informational)"
elif [ -z "$REGISTER_SOCKET" ]; then
    info "claweed doctor skipped — no register socket known (set CLAWEE_REGISTER_SOCKET)"
else
    printf '\n'
    # Informational only: a ✗ check must not fail the install (|| true).
    "$CLAWEED_BIN" doctor --data-dir "$DATA_DIR" --spawn-helper "$SPAWN_HELPER" \
        --register-socket "$REGISTER_SOCKET" 2>&1 || true
fi

# =========================================================================
# FULL DISK ACCESS (macOS): the pty session runs the operator's shell + commands
#   as this user — BOTH claweed (the broker) and clawee-spawn (the setuid pty
#   launcher) must reach TCC-protected dirs (Desktop / Documents / Downloads / …).
#   macOS grants FDA PER BINARY, and both are ad-hoc-signed (signature changes on
#   every build), so FDA must be (re)granted whenever a NEW binary is laid down.
#   Surface it on macOS: open the FDA pane + name the exact binaries to add. When
#   both were byte-identical, the prior grants still apply — just remind.
# =========================================================================
if [ "$OS" = darwin ]; then
    # clawee-spawn was actually installed this run (had sudo, not skipped).
    SPAWN_INSTALLED=0
    [ "$SPAWN_SKIPPED" -eq 0 ] && SPAWN_INSTALLED=1
    # A re-grant is needed when EITHER binary's signature changed: claweed always
    # (CLAWEED_SAME), clawee-spawn only when it was installed and differed.
    FDA_REGRANT=0
    [ "$CLAWEED_SAME" -eq 0 ] && FDA_REGRANT=1
    [ "$SPAWN_INSTALLED" -eq 1 ] && [ "$SPAWN_SAME" -eq 0 ] && FDA_REGRANT=1
    if [ "$FDA_REGRANT" -eq 0 ]; then
        info "Full Disk Access: claweed + clawee-spawn unchanged — your existing grants still apply."
    else
        printf '\n'
        warn "ACTION REQUIRED — grant Full Disk Access (macOS), required for pty sessions:"
        warn "  the remote shell + the operator's commands run as you and must reach your"
        warn "  files. Add BOTH of these binaries and toggle them ON:"
        warn "    $CLAWEED_BIN   (the broker)"
        if [ "$SPAWN_INSTALLED" -eq 1 ]; then
            warn "    $SPAWN_HELPER   (the setuid pty launcher)"
        else
            warn "    $SPAWN_HELPER   (the setuid pty launcher — once you run the printed Tier-S sudo block to install it)"
        fi
        warn "  in  System Settings ▸ Privacy & Security ▸ Full Disk Access."
        if open "x-apple.systempreferences:com.apple.preference.security?Privacy_AllFiles" 2>/dev/null; then
            warn "  (opened the Full Disk Access pane — click + then ⌘⇧G to paste each path, or drag the binary in;"
            warn "   the claweed folder is hidden, so the + / ⌘⇧G route is easiest — then toggle each ON.)"
        else
            warn "  (open that pane by hand — no GUI to open it from here.)"
        fi
    fi
fi

# =========================================================================
# COMPLETION: non-zero exit if the Tier-S spawn step or the system boot unit
#   was skipped/deferred, so callers (and the operator) know the install isn't
#   fully done until the printed block(s) run.
# =========================================================================
if [ "$SPAWN_SKIPPED" -eq 1 ] || [ "$BOOT_DEFERRED" -eq 1 ]; then
    [ "$SPAWN_SKIPPED" -eq 1 ] && printf '\n  ! claweed installed, but the spawn helper is NOT installed — run the printed Tier-S sudo block to finish.\n' >&2
    [ "$BOOT_DEFERRED" -eq 1 ] && printf '\n  ! claweed installed, but the SYSTEM boot unit is NOT in place — run the printed sudo block to finish.\n' >&2
    printf '\n' >&2
    exit 3
fi

printf '\n  \xe2\x9c\x93 claweed install complete (local-source, %s)\n\n' "$VERSION"
