#!/bin/sh
# ============================ GENERATED REFERENCE COPY =====================
# DO NOT EDIT THIS FILE. Canonical source: the daemon repo's
# install/install.sh.in (clawee-git/daemon). tools/release.sh renders THAT
# template at cut time (sed s/__CLAWEED_VERSION__/<stamp>/) — the release zip
# NEVER ships this copy; it exists only so repo-local shellcheck + reviews
# audit the same code that ships. Refresh whenever the canonical template
# changes: re-render it with __CLAWEED_VERSION__ -> (rendered-at-build) and
# keep this header block. Last synced: 2026-07-06 (daemon @ 2a232e1).
# ===========================================================================
# claweed installer — LOCAL-SOURCE variant (POSIX sh, macOS + Linux).
#
# This is the Phase-B `claweed` release-component installer (it installs the
# claweed PTY daemon + the setuid clawee-spawn helper, and cross-installs the
# burrowee-gateway dependency), in a variant that sources clawee's OWN binaries
# from this staged directory instead of a signed GitHub release fronted by
# release.clawee.org. It is generated + staged by install/build-local.sh; the
# claweed + clawee-spawn binaries sit alongside this script.
#
# SUDO-MINIMAL model. Run this AS THE USER — do NOT prefix it with sudo. Almost
# everything (the claweed binary, the data-dir, the launchd/systemd boot unit in
# your own user domain, the gateway dependency, the doctor tail) installs with NO
# privilege. The script escalates with `sudo` for EXACTLY ONE tier: the
# setuid-root spawn helper + its root-owned allowlist (Tier S). If passwordless
# sudo isn't available, the rest of the install still completes and the exact
# Tier-S sudo block is printed for you to run by hand.
#
# Usage (from the staged dir):
#   sh ./install.sh                 # interactive: prompts before the boot step
#   sh ./install.sh --yes           # unattended: assume-yes; also loads the boot unit
#   sh ./install.sh uninstall       # remove claweed + the setuid helper (keeps data)
#   sh ./install.sh uninstall --purge   # also remove ~/.clawee/data (tenant trust keys!)
#
# Env:
#   CLAWEE_PREFIX           install root for the USER-tier claweed binary
#                           (default: ~/.local/bin; user-writable, no sudo)
#   CLAWEE_REGISTER_SOCKET  burrowee-gateway register socket the daemon dials
#                           (default: auto-detected from the running gateway)
#   CLAWEE_DATA_DIR         claweed --data-dir (default: ~/.clawee/data)
#
# Only clawee's own channel is replaced by this local source; the burrowee
# dependency still installs from burrowee's PUBLIC channel
# (release.burrowee.com/gateway/install.sh).
set -eu

# ---- knobs --------------------------------------------------------------
# Tier U (no sudo): the claweed binary lands in a USER-writable prefix.
PREFIX="${CLAWEE_PREFIX:-$HOME/.local/bin}"
CLAWEED_BIN="$PREFIX/claweed"

# Tier S (sudo only): the setuid spawn helper + allowlist MUST live in a
# root-owned, NON-user-writable dir. A user-writable setuid-root binary is a
# trivial local-root escalation (anyone overwrites it, then triggers it as
# root) — so these paths are HARDCODED to /usr/local and are NEVER derived from
# CLAWEE_PREFIX. Do not move them under ~/.local/bin or any user-writable root.
SPAWN_DIR="/usr/local/bin"
SPAWN_HELPER="$SPAWN_DIR/clawee-spawn"
ETC_DIR="/usr/local/etc/clawee"
ALLOW_FILE="$ETC_DIR/spawn-allow"
# Legacy: the old all-sudo installer put claweed here. We clean it up below.
LEGACY_CLAWEED_BIN="/usr/local/bin/claweed"

LABEL="org.clawee.claweed"
VERSION="(rendered-at-build)"

# Minimum burrowee-gateway version this claweed expects (the register-link
# contract floor). Empty = accept any installed gateway; only install when none.
GATEWAY_FLOOR=""

# ---- helpers ------------------------------------------------------------
fail() { printf '\n  \xe2\x9c\x97 %s\n\n' "$*" >&2; exit 1; }
info() { printf '  \xe2\x86\x92 %s\n' "$*"; }
ok()   { printf '  \xe2\x9c\x93 %s\n' "$*"; }
warn() { printf '  ! %s\n' "$*" >&2; }

# sq VALUE — emit VALUE safely single-quoted for embedding in GENERATED shell
# (the root finisher). It wraps the value in single quotes and replaces every
# embedded single quote with the '\'' escape sequence, so a value containing a
# quote (or any metacharacter) can never break out of the quoting and inject
# commands into the script that later runs under `sudo sh` (M4). Use it for EVERY
# baked path/value in the finisher heredoc. Example: sq "a'b" -> 'a'\''b'.
sq() {
    printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

# tilde_path PATH — render an absolute path for the printed copy-paste blocks
# with a leading $HOME rewritten to a literal ~, so the commands carry no
# machine-specific home and each operator's shell re-expands ~ to THEIR own home.
# The ~ is emitted OUTSIDE the quotes (tilde expansion never happens inside
# quotes; POSIX exempts the expanded home from field splitting, so a space in
# $HOME is still safe) while the remainder stays single-quoted to survive spaces
# and shell metacharacters — matching this script's quoting discipline. Paths
# outside $HOME are single-quoted whole.
tilde_path() {
    case "$1" in
        "$HOME"/*) printf "~/'%s'" "${1#"$HOME"/}" ;;
        "$HOME")   printf '~' ;;
        *)         printf "'%s'" "$1" ;;
    esac
}

# ---- argument parse -----------------------------------------------------
# install.sh                 -> install (default)
# install.sh uninstall [...]  -> uninstall mode
# --yes/-y                   -> assume-yes (install: load boot unit unattended)
# --purge                    -> uninstall: also remove the data-dir
# -h/--help                  -> usage
MODE=install
ASSUME_YES=0
PURGE=0
# Auto-restart claweed after an in-place update (default ON). When the service is
# already running — e.g. `claweed update` invoked from inside a claweed-brokered
# session — the boot step (re)starts it on the new binary WITHOUT prompting, via
# the service manager so it survives this session being torn down. --no-restart /
# CLAWEE_NO_RESTART=1 opts out (restart by hand later).
NO_RESTART=0
[ "${CLAWEE_NO_RESTART:-0}" = 1 ] && NO_RESTART=1
# Update mode — set by `claweed update` (via CLAWEE_UPDATE_MODE env) or the flags:
#   dry    — print what would change (binary / spawn / boot-unit) + whether a
#            restart is required, then STOP (no changes).
#   apply  — print the plan, PROMPT, apply on yes; restart only if changed.
#   auto   — apply unattended (no prompt); restart only if changed.
#   force  — apply, REPLACING EVERYTHING even if identical; always restart.
# Empty = the normal interactive install (a fresh install / direct run).
UPDATE_MODE="${CLAWEE_UPDATE_MODE:-}"
usage() {
    cat <<EOF
claweed installer ($VERSION) — sudo-minimal

  sh ./install.sh [--yes] [--no-restart]   install (run AS THE USER, not sudo)
  sh ./install.sh --dry|--auto|--force     update: plan-only / apply / replace-all
  sh ./install.sh uninstall [--purge]      remove claweed + the setuid helper
  sh ./install.sh -h                       this help

  --dry         print the update plan (what would change + restart-required), no changes
  --auto        apply the update unattended; restart only if changed
  --force       reinstall everything (binary + spawn + boot-unit) + restart
  --yes         unattended install; load the boot unit without prompting
  --no-restart  apply, but don't restart a running claweed afterward
  --purge       uninstall only: also delete ~/.clawee/data (TENANT TRUST KEYS)
EOF
}
# Consume an optional leading subcommand (install|uninstall), then flags.
case "${1:-}" in
    uninstall|--uninstall) MODE=uninstall; shift ;;
    install) MODE=install; shift ;;
esac
for arg in "$@"; do
    case "$arg" in
        --yes|-y)     ASSUME_YES=1 ;;
        --no-restart) NO_RESTART=1 ;;
        --dry)        UPDATE_MODE=dry ;;
        --auto)       UPDATE_MODE=auto ;;
        --force)      UPDATE_MODE=force ;;
        --purge)      PURGE=1 ;;
        -h|--help)    usage; exit 0 ;;
        *) fail "unknown argument: $arg (try: sh ./install.sh -h)" ;;
    esac
done

# Derive the apply posture from the update mode (set by `claweed update`):
#   dry   — compute + print the plan, then exit (no changes).
#   apply — print the plan, PROMPT [y/N], apply on yes (the default).
#   auto  — apply unattended (assume-yes), no prompt.
#   force — apply, replacing everything even if identical.
# All apply modes restart ONLY when the binary or boot-unit changed (RESTART_NEEDED,
# computed in the plan) — except force, which always restarts. --no-restart skips it.
PLAN_ONLY=0
FORCE_REPLACE=0
case "$UPDATE_MODE" in
    dry)   PLAN_ONLY=1 ;;
    apply) ;;                              # prompts (ASSUME_YES stays 0)
    auto)  ASSUME_YES=1 ;;
    force) ASSUME_YES=1; FORCE_REPLACE=1 ;;
    "")    ;;  # interactive fresh install / direct run
    *)     fail "invalid CLAWEE_UPDATE_MODE: $UPDATE_MODE (dry|apply|auto|force)" ;;
esac

# semver_lt A B — exit 0 iff version A is strictly older than B. Portable
# (no GNU `sort -V`): strips a leading 'v', splits on '.', compares fields
# numerically left-to-right, missing fields treated as 0. Non-numeric/garbage
# fields compare as 0.
semver_lt() {
    awk -v a="$1" -v b="$2" '
        function norm(s,   t) { sub(/^v/, "", s); return s }
        BEGIN {
            na = split(norm(a), x, ".")
            nb = split(norm(b), y, ".")
            n = (na > nb) ? na : nb
            for (i = 1; i <= n; i++) {
                xi = (i <= na) ? x[i] + 0 : 0
                yi = (i <= nb) ? y[i] + 0 : 0
                if (xi < yi) { exit 0 }
                if (xi > yi) { exit 1 }
            }
            exit 1   # equal -> not strictly less
        }'
}

# confirm PROMPT — returns 0 on yes. --yes makes it unconditional.
confirm() {
    [ "$ASSUME_YES" -eq 1 ] && return 0
    [ -r /dev/tty ] || { warn "no tty for prompt; re-run with --yes to proceed unattended"; return 1; }
    printf '  %s [y/N] ' "$1" >/dev/tty
    ans=''
    IFS= read -r ans </dev/tty || ans=''
    case "$ans" in y|Y|yes|YES) return 0 ;; *) return 1 ;; esac
}

# ---- identity + data-dir ------------------------------------------------
# This script runs AS THE INVOKING USER (no leading sudo), so id/$HOME are the
# real human's. The spawn allowlist trusts THIS uid — it's the uid claweed runs
# as. The data-dir is this user's ~/.clawee/data.
USER_UID="$(id -u)"
USER_NAME="$(id -un)"
DATA_DIR="${CLAWEE_DATA_DIR:-$HOME/.clawee/data}"

# ---- platform detection -------------------------------------------------
case "$(uname -s)" in
    Darwin) OS=darwin ;;
    Linux)  OS=linux ;;
    *)      fail "unsupported OS: $(uname -s) (claweed ships darwin + linux only)" ;;
esac
case "$(uname -m)" in
    arm64|aarch64) ARCH=arm64 ;;
    x86_64|amd64)  ARCH=amd64 ;;
    *)             fail "unsupported arch: $(uname -m)" ;;
esac
KIND=$( [ "$OS" = darwin ] && echo launchd || echo systemd )

# resolve the directory holding this script (the staged dir with the binaries).
SELF_DIR="$(cd "$(dirname "$0")" && pwd)"

# =========================================================================
# UNINSTALL MODE
# =========================================================================
if [ "$MODE" = uninstall ]; then
    printf '\n  claweed uninstaller  %s  (%s/%s)\n\n' "$VERSION" "$OS" "$ARCH"

    # ---- Tier U (no sudo): boot unit + user binary + (optionally) data ---
    if [ "$OS" = darwin ]; then
        UNIT_PATH="$HOME/Library/LaunchAgents/$LABEL.plist"
        if launchctl bootout "gui/$USER_UID/$LABEL" 2>/dev/null; then
            ok "unloaded LaunchAgent (gui/$USER_UID/$LABEL)"
        else
            info "LaunchAgent not loaded — nothing to unload"
        fi
        if [ -f "$UNIT_PATH" ]; then
            rm -f "$UNIT_PATH"; ok "removed $UNIT_PATH"
        else
            info "no LaunchAgent plist at $UNIT_PATH — skipped"
        fi
    else
        UNIT_PATH="$HOME/.config/systemd/user/claweed.service"
        if systemctl --user disable --now claweed.service 2>/dev/null; then
            ok "disabled + stopped systemd user unit"
        else
            info "systemd user unit not active — nothing to disable"
        fi
        if [ -f "$UNIT_PATH" ]; then
            rm -f "$UNIT_PATH"
            systemctl --user daemon-reload 2>/dev/null || true
            ok "removed $UNIT_PATH"
        else
            info "no systemd unit at $UNIT_PATH — skipped"
        fi
    fi

    if [ -f "$CLAWEED_BIN" ]; then
        rm -f "$CLAWEED_BIN" && ok "removed $CLAWEED_BIN"
    else
        info "no claweed binary at $CLAWEED_BIN — skipped"
    fi

    CLAWEED_UPDATER_BIN="$PREFIX/claweed-updater"
    if [ -f "$CLAWEED_UPDATER_BIN" ]; then
        rm -f "$CLAWEED_UPDATER_BIN" && ok "removed $CLAWEED_UPDATER_BIN"
    else
        info "no claweed-updater binary at $CLAWEED_UPDATER_BIN — skipped"
    fi

    # Staged setuid source + generated finisher left by an install that deferred
    # the Tier-S step (the live setuid copy in /usr/local is removed in Tier S
    # below).
    if [ -f "$HOME/.clawee/clawee-spawn" ]; then
        rm -f "$HOME/.clawee/clawee-spawn" && ok "removed staged $HOME/.clawee/clawee-spawn"
    fi
    if [ -f "$HOME/.clawee/clawee-spawn-setup.sh" ]; then
        rm -f "$HOME/.clawee/clawee-spawn-setup.sh" && ok "removed staged $HOME/.clawee/clawee-spawn-setup.sh"
    fi

    if [ "$PURGE" -eq 1 ]; then
        if [ -d "$DATA_DIR" ]; then
            warn "--purge: removing the data-dir $DATA_DIR (this deletes tenant trust keys; enrolled devices must re-enroll)"
            rm -rf "$DATA_DIR" && ok "removed data-dir $DATA_DIR"
        else
            info "no data-dir at $DATA_DIR — skipped"
        fi
    else
        if [ -d "$DATA_DIR" ]; then
            info "kept data-dir $DATA_DIR (holds tenant trust keys; pass --purge to remove)"
        fi
    fi

    # ---- Tier S (sudo, only if anything root-owned is present) -----------
    NEED_TIER_S=0
    [ -e "$SPAWN_HELPER" ] && NEED_TIER_S=1
    [ -e "$ALLOW_FILE" ] && NEED_TIER_S=1
    [ -e "$LEGACY_CLAWEED_BIN" ] && NEED_TIER_S=1
    if [ "$NEED_TIER_S" -eq 0 ]; then
        info "no root-owned spawn helper / allowlist present — nothing for sudo to remove"
        printf '\n  \xe2\x9c\x93 claweed uninstalled (local-source, %s)\n\n' "$VERSION"
        exit 0
    fi

    SUDO=""
    if [ "$USER_UID" -eq 0 ]; then
        SUDO=""
    elif sudo -n true 2>/dev/null; then
        SUDO="sudo"
    else
        cat >&2 <<EOF

  ! the setuid spawn helper + allowlist are root-owned — passwordless sudo is
    not available, so remove them by hand:

      sudo rm -f '$SPAWN_HELPER' '$ALLOW_FILE'
      sudo rmdir '$ETC_DIR' 2>/dev/null || true
EOF
        if [ -e "$LEGACY_CLAWEED_BIN" ]; then
            printf "      sudo rm -f '%s'   # legacy all-sudo install\n" "$LEGACY_CLAWEED_BIN" >&2
        fi
        printf '\n' >&2
        warn "claweed uninstalled (user tier); the root-owned spawn tier was left for the manual block above"
        exit 4
    fi

    if [ -e "$SPAWN_HELPER" ]; then
        $SUDO rm -f "$SPAWN_HELPER" && ok "removed $SPAWN_HELPER"
    fi
    if [ -e "$ALLOW_FILE" ]; then
        $SUDO rm -f "$ALLOW_FILE" && ok "removed $ALLOW_FILE"
    fi
    # rmdir only when empty — never recursive (it's a shared /usr/local tree).
    if [ -d "$ETC_DIR" ] && $SUDO rmdir "$ETC_DIR" 2>/dev/null; then
        ok "removed empty $ETC_DIR"
    fi
    if [ -e "$LEGACY_CLAWEED_BIN" ]; then
        $SUDO rm -f "$LEGACY_CLAWEED_BIN" && ok "removed legacy $LEGACY_CLAWEED_BIN"
    fi

    printf '\n  \xe2\x9c\x93 claweed uninstalled (local-source, %s)\n\n' "$VERSION"
    exit 0
fi

# =========================================================================
# INSTALL MODE
# =========================================================================
printf '\n  claweed installer (local-source)  %s  (%s/%s)\n\n' "$VERSION" "$OS" "$ARCH"

# Refuse a blanket-sudo run: under sudo $HOME/id are root's, so the whole
# user tier would land in root's home + trust root's uid — exactly the old
# broken model this restructure removes. Tier S escalates per-command instead.
if [ "$USER_UID" -eq 0 ] && [ -n "${SUDO_USER:-}" ]; then
    fail "don't run this under sudo — run it AS YOUR USER (the script escalates with sudo only for the spawn helper). Re-run: sh ./install.sh"
fi

# ---- preflight: staged binaries present ---------------------------------
for b in claweed clawee-spawn claweed-updater; do
    [ -f "$SELF_DIR/$b" ] || fail "missing $b in $SELF_DIR — re-run build-local.sh to stage the binaries"
done

# ---- register socket (detect early; unprivileged) -----------------------
# Resolve the burrowee-gateway register.sock the daemon dials: explicit env
# wins; else detect from open unix sockets. Done up front so the PLAN below can
# render the boot unit to compare, and the Tier-S manual hint can quote the real
# path. lsof can return several matches (multiple gateways) — auto-use a UNIQUE
# match; on >1 prefer THIS user's home gateway when present, else leave empty.
REGISTER_SOCKET="${CLAWEE_REGISTER_SOCKET:-}"
if [ -z "$REGISTER_SOCKET" ] && command -v lsof >/dev/null 2>&1; then
    # Use lsof's field output (-F n) so the socket NAME is on its own line (n-prefixed),
    # not the whitespace-split last column of the human table — a path containing a
    # space (e.g. a $HOME with a space) would otherwise be truncated by `awk $NF`.
    socket_matches="$(lsof -U -F n 2>/dev/null \
        | sed -n 's/^n//p' \
        | grep '/register\.sock$' \
        | sort -u)"
    match_count="$(printf '%s' "$socket_matches" | grep -c . || true)"
    if [ "$match_count" -eq 1 ]; then
        REGISTER_SOCKET="$socket_matches"
    elif [ "$match_count" -gt 1 ]; then
        # Several gateways' sockets are open (e.g. a CI/bare gateway under /tmp
        # alongside the real one). Prefer THIS user's canonical home gateway when
        # it is among the matches; only bail when it isn't.
        home_sock="$HOME/.burrowee/gateway/sockets/register.sock"
        if printf '%s\n' "$socket_matches" | grep -qxF "$home_sock"; then
            REGISTER_SOCKET="$home_sock"
            [ "$PLAN_ONLY" -eq 1 ] || info "multiple register sockets found — auto-picked the home gateway -> $home_sock"
        else
            warn "multiple burrowee-gateway register sockets found — cannot auto-pick:"
            printf '%s\n' "$socket_matches" | while IFS= read -r s; do warn "    $s"; done
            warn "set CLAWEE_REGISTER_SOCKET=<path> and re-run to choose one"
        fi
    fi
fi

# unit_path_for echoes the boot-unit path for the current OS (used by the plan +
# the boot-unit step).
unit_path_for() {
    if [ "$OS" = darwin ]; then echo "$HOME/Library/LaunchAgents/$LABEL.plist"
    else echo "$HOME/.config/systemd/user/claweed.service"; fi
}

# spawn_unchanged / unit_unchanged are the idempotency checks shared by the PLAN
# and the apply steps: 0 = would change (or force), 1 = byte-identical.
spawn_unchanged() {
    [ "$FORCE_REPLACE" -eq 0 ] \
        && [ -f "$SPAWN_HELPER" ] && cmp -s "$SELF_DIR/clawee-spawn" "$SPAWN_HELPER" \
        && [ -f "$ALLOW_FILE" ] && grep -qx "$USER_UID" "$ALLOW_FILE" 2>/dev/null
}
unit_unchanged() {
    # Render the would-be unit with the STAGED claweed (the plan runs before the
    # binary is installed) and cmp against the installed unit. No socket / render
    # failure / force ⇒ "changed".
    [ "$FORCE_REPLACE" -eq 0 ] && [ -n "$REGISTER_SOCKET" ] || return 1
    _up="$(unit_path_for)"; [ -f "$_up" ] || return 1
    _tmp="$(mktemp)"; _kind=$( [ "$OS" = darwin ] && echo launchd || echo systemd )
    if [ "$OS" = darwin ]; then
        "$SELF_DIR/claweed" print-boot-unit --kind="$_kind" --claweed "$CLAWEED_BIN" \
            --data-dir "$DATA_DIR" --spawn-helper "$SPAWN_HELPER" \
            --register-socket "$REGISTER_SOCKET" --log "$HOME/Library/Logs/claweed.log" >"$_tmp" 2>/dev/null
    else
        "$SELF_DIR/claweed" print-boot-unit --kind="$_kind" --claweed "$CLAWEED_BIN" \
            --data-dir "$DATA_DIR" --spawn-helper "$SPAWN_HELPER" \
            --register-socket "$REGISTER_SOCKET" --user "$USER_NAME" >"$_tmp" 2>/dev/null
    fi
    _r=1; cmp -s "$_tmp" "$_up" || _r=0; rm -f "$_tmp"; [ "$_r" -eq 1 ]
}

# =========================================================================
# PLAN — what would change. Printed for every update mode (dry / apply / auto /
# force). dry STOPS here; apply PROMPTS before applying; auto/force assume-yes.
# =========================================================================
RESTART_NEEDED=0
if [ -n "$UPDATE_MODE" ]; then
    installed_ver="$("$CLAWEED_BIN" --version 2>/dev/null | awk '{print $NF}')"
    [ -n "$installed_ver" ] || installed_ver="(none)"
    bin_changed=1; [ "$FORCE_REPLACE" -eq 0 ] && [ "$installed_ver" = "$VERSION" ] && bin_changed=0
    spawn_unchanged && spawn_line="unchanged" || spawn_line="REPLACE"
    unit_unchanged && unit_line="unchanged" || unit_line="REWRITE"
    [ "$bin_changed" -eq 1 ] && bin_line="$installed_ver -> $VERSION   REPLACE" || bin_line="$VERSION   unchanged"
    # A restart is needed only when the binary or the boot unit changes — replacing
    # the setuid spawn helper alone does NOT bounce claweed. force always restarts.
    if [ "$FORCE_REPLACE" -eq 1 ] || [ "$bin_changed" -eq 1 ] || [ "$unit_line" = "REWRITE" ]; then
        RESTART_NEEDED=1
    fi
    [ "$RESTART_NEEDED" -eq 1 ] && restart_line="required" || restart_line="not required"
    printf '\n  update plan (%s):\n' "$VERSION"
    printf '    claweed binary   %s\n' "$bin_line"
    printf '    clawee-spawn     %s\n' "$spawn_line"
    printf '    boot-unit        %s\n' "$unit_line"
    printf '    restart claweed  %s\n\n' "$restart_line"
    if [ "$PLAN_ONLY" -eq 1 ]; then
        info "plan only (--dry) — nothing changed. apply with --auto, or --force to replace everything."
        exit 0
    fi
    # apply mode prompts here; auto/force assume-yes (ASSUME_YES → confirm returns 0).
    confirm "apply this update?" || { info "update skipped."; exit 0; }
fi

# =========================================================================
# TIER U (no sudo): claweed -> $PREFIX (0755), as the invoking user.
# =========================================================================
info "installing claweed -> $PREFIX"
mkdir -p "$PREFIX" || fail "could not create $PREFIX (set CLAWEE_PREFIX to a writable dir)"
[ -w "$PREFIX" ] || fail "$PREFIX is not writable — set CLAWEE_PREFIX to a user-writable dir"
# Detect whether the claweed binary actually changes BEFORE overwriting it: a
# byte-identical binary keeps its macOS Full-Disk-Access grant, a changed one
# (new ad-hoc signature) needs a re-grant. Mirrors spawn_unchanged for the FDA
# block below. Set under set -eu via the &&-list exemption (like SPAWN_SAME).
CLAWEED_SAME=0
[ -f "$CLAWEED_BIN" ] && cmp -s "$SELF_DIR/claweed" "$CLAWEED_BIN" && CLAWEED_SAME=1
install -m 0755 "$SELF_DIR/claweed" "$CLAWEED_BIN"
[ "$OS" = darwin ] && xattr -d com.apple.quarantine "$CLAWEED_BIN" 2>/dev/null || true
ok "claweed installed: $($CLAWEED_BIN --version 2>/dev/null || echo claweed)"

# claweed-updater — one-shot update trigger; no service unit.
CLAWEED_UPDATER_BIN="$PREFIX/claweed-updater"
install -m 0755 "$SELF_DIR/claweed-updater" "$CLAWEED_UPDATER_BIN"
[ "$OS" = darwin ] && xattr -d com.apple.quarantine "$CLAWEED_UPDATER_BIN" 2>/dev/null || true
ok "claweed-updater installed: $CLAWEED_UPDATER_BIN"

# PATH hint: ~/.local/bin is frequently NOT on PATH.
if ! command -v claweed >/dev/null 2>&1; then
    warn "claweed is not on PATH yet — add $PREFIX to PATH:"
    warn "  export PATH=\"$PREFIX:\$PATH\"   # add to ~/.profile or your shell rc"
else
    case ":$PATH:" in
        *":$PREFIX:"*) ;;
        *) warn "$PREFIX is not on PATH — add: export PATH=\"$PREFIX:\$PATH\"" ;;
    esac
fi

# ---- data-dir (this user's ~/.clawee/data, 0700) — no sudo --------------
# Never clobber an existing data-dir — it holds tenant trust keys. Only create
# (0700) when absent; leave an existing one untouched.
if [ -d "$DATA_DIR" ]; then
    ok "data-dir exists -> $DATA_DIR (left untouched)"
else
    info "creating data-dir -> $DATA_DIR (0700)"
    install -d -m 700 "$DATA_DIR" || fail "could not create data-dir $DATA_DIR"
    ok "data-dir ready"
fi

# =========================================================================
# TIER S (sudo, ONLY this): setuid clawee-spawn + root-owned allowlist.
#
#   SECURITY INVARIANT: the setuid-root binary stays root-owned in a
#   NON-user-writable dir (/usr/local/bin), and the allowlist stays root-owned,
#   non-group/world-writable (0644). A user-writable setuid file would let any
#   local user overwrite it and run arbitrary code as root.
#
#   need_sudo posture: run the Tier-S commands with sudo if we already are root
#   or passwordless sudo works; otherwise PRINT the exact Tier-S block (the rest
#   of the install is done — the spawn helper is the only remainder) and exit
#   non-zero so the operator knows to run it.
# =========================================================================
# Tier-S idempotency (the common `claweed update` case): when the installed setuid
# helper is byte-identical to the staged one AND the allowlist already trusts this
# uid (and we're not --force), the whole privileged tier is a no-op — skip it
# entirely (no sudo, no password prompt, no macOS Full-Disk-Access re-grant). The
# shared spawn_unchanged() reads the root-owned files unprivileged (4755 helper +
# 0644 allowlist are both world-readable) and honours FORCE_REPLACE.
SPAWN_SAME=0
spawn_unchanged && SPAWN_SAME=1

SPAWN_SKIPPED=0
SUDO=""
if [ "$SPAWN_SAME" -eq 1 ]; then
    ok "clawee-spawn + allowlist unchanged -> $SPAWN_HELPER (skipped — no sudo)"
elif [ "$USER_UID" -eq 0 ]; then
    SUDO=""
elif sudo -n true 2>/dev/null; then
    SUDO="sudo"                       # passwordless — run silently
elif [ -r /dev/tty ]; then
    # No passwordless sudo, but a terminal is attached: run the ONE privileged
    # step interactively. sudo reads the password from /dev/tty (not stdin), so
    # this works even under `curl … | sh` — the same /dev/tty the confirm()
    # prompt already uses. Only when there is NO tty (CI / fully unattended) do
    # we skip and leave the printed block + saved script for a later manual run.
    SUDO="sudo"
    info "the one privileged step (setuid clawee-spawn) needs sudo — you'll be prompted for your password"
else
    SPAWN_SKIPPED=1
fi

if [ "$SPAWN_SAME" -eq 1 ]; then
    : # spawn helper + allowlist already current — nothing to install (handled above)
elif [ "$SPAWN_SKIPPED" -eq 1 ]; then
    # No passwordless sudo, so the ONE privileged step (setuid clawee-spawn +
    # root-owned allowlist) can't run inline. Stage the setuid SOURCE to a
    # durable, user-owned path AND write the privileged step out as a small
    # script the operator runs once with `sudo sh`. Both live in $HOME/.clawee
    # (the user's own tree) so they survive this installer's temp dir being
    # cleaned up before the operator gets to them; a non-setuid copy there is
    # harmless (it refuses to run without setuid), and the script's
    # `install -m 4755 -o root` makes the privileged copy in the root-owned dir.
    #
    # The generated script bakes ABSOLUTE paths + the invoking uid: it runs as
    # root under sudo, where ~ / $HOME would resolve to root's home, not this
    # user's — so a literal ~ there would point at the wrong tree.
    CLAWEE_HOME="$HOME/.clawee"
    mkdir -p "$CLAWEE_HOME"
    chmod 0700 "$CLAWEE_HOME" 2>/dev/null || true   # holds a soon-setuid binary + a root-run script

    STAGED_SPAWN="$CLAWEE_HOME/clawee-spawn"
    cp "$SELF_DIR/clawee-spawn" "$STAGED_SPAWN"
    chmod 0755 "$STAGED_SPAWN"
    [ "$OS" = darwin ] && xattr -d com.apple.quarantine "$STAGED_SPAWN" 2>/dev/null || true

    # Write the privileged finisher. Escaped \$(id -u) / \$0 stay live in the
    # generated file; every other value bakes its (absolute, root-safe) value now,
    # safely single-quoted via sq() so a path containing a single quote (e.g. a
    # $HOME with a ') can never break out of the quoting and inject commands into
    # the script that then runs under `sudo sh` (M4). Each sq'd value ALREADY
    # carries its surrounding single quotes, so the heredoc references them bare.
    SETUP_SCRIPT="$CLAWEE_HOME/clawee-spawn-setup.sh"
    Q_STAGED_SPAWN="$(sq "$STAGED_SPAWN")"
    Q_SPAWN_HELPER="$(sq "$SPAWN_HELPER")"
    Q_ETC_DIR="$(sq "$ETC_DIR")"
    Q_ALLOW_FILE="$(sq "$ALLOW_FILE")"
    Q_USER_UID="$(sq "$USER_UID")"
    {
        cat <<EOF
#!/bin/sh
# clawee-spawn privileged finisher — generated by the claweed installer.
# The user-tier install is done; this installs the ONE thing that needs root:
# the setuid-root clawee-spawn helper (into a root-owned, non-user-writable dir)
# and its root-owned allowlist. Run as root:  sudo sh <this file>
# Idempotent; safe to re-run. The installer's uninstall mode removes it.
set -eu
if [ "\$(id -u)" -ne 0 ]; then
    echo "clawee-spawn-setup: run me as root — e.g.  sudo sh \$0" >&2
    exit 1
fi
install -m 4755 -o root $Q_STAGED_SPAWN $Q_SPAWN_HELPER
mkdir -p $Q_ETC_DIR
printf '%s\n' $Q_USER_UID > $Q_ALLOW_FILE
chown root $Q_ALLOW_FILE
chmod 0644 $Q_ALLOW_FILE
EOF
        if [ -e "$LEGACY_CLAWEED_BIN" ]; then
            printf 'rm -f %s   # legacy all-sudo install of claweed\n' "$(sq "$LEGACY_CLAWEED_BIN")"
        fi
        printf 'echo "  clawee-spawn installed setuid-root; allowlist authorizes uid %s"\n' "$USER_UID"
    } > "$SETUP_SCRIPT"
    chmod 0755 "$SETUP_SCRIPT"

    # Show the run + verify commands home-relative (~) so no machine-specific
    # path is printed; the operator's shell re-expands ~ to their own home, and
    # `sudo sh` then runs the script (which itself uses the baked absolute paths).
    SETUP_DISP="$(tilde_path "$SETUP_SCRIPT")"
    CLAWEED_BIN_DISP="$(tilde_path "$CLAWEED_BIN")"
    cat >&2 <<EOF

  ! Tier S (the ONLY privileged step) was skipped — no passwordless sudo.
    claweed is installed; one privileged step remains. I wrote it to a script —
    run it once as root, then verify as yourself:

      sudo sh $SETUP_DISP
      $CLAWEED_BIN_DISP status

EOF
else
    info "installing clawee-spawn setuid-root (4755) -> $SPAWN_HELPER"
    $SUDO install -m 4755 -o root "$SELF_DIR/clawee-spawn" "$SPAWN_HELPER"
    [ "$OS" = darwin ] && $SUDO xattr -d com.apple.quarantine "$SPAWN_HELPER" 2>/dev/null || true
    ok "clawee-spawn installed setuid-root (root-owned, non-user-writable dir)"

    info "writing spawn allowlist (uid $USER_UID, user $USER_NAME) -> $ALLOW_FILE"
    $SUDO mkdir -p "$ETC_DIR"
    printf '%s\n' "$USER_UID" | $SUDO tee "$ALLOW_FILE" >/dev/null
    $SUDO chown root "$ALLOW_FILE"
    $SUDO chmod 0644 "$ALLOW_FILE"
    ok "allowlist written (root-owned, 0644)"

    # Legacy cleanup: the old all-sudo installer placed claweed in /usr/local/bin.
    # The user-tier binary now lives in $PREFIX, so a stale copy there shadows it
    # on PATH — offer to remove it (Tier S, sudo).
    if [ -e "$LEGACY_CLAWEED_BIN" ] && [ "$LEGACY_CLAWEED_BIN" != "$CLAWEED_BIN" ]; then
        if confirm "remove the legacy root-owned $LEGACY_CLAWEED_BIN (from the old all-sudo install)?"; then
            $SUDO rm -f "$LEGACY_CLAWEED_BIN" && ok "removed legacy $LEGACY_CLAWEED_BIN"
        else
            warn "kept $LEGACY_CLAWEED_BIN — it may shadow $CLAWEED_BIN on PATH; remove with: sudo rm -f '$LEGACY_CLAWEED_BIN'"
        fi
    fi
fi

# =========================================================================
# DEPENDENCY: burrowee-gateway (cross-channel, PUBLIC burrowee installer)
#   No sudo here — burrowee's own installer escalates as it needs to. Install
#   when missing or older than floor; never downgrades. This is the ONE step
#   that stays public in this variant.
# =========================================================================
dep_burrowee_gateway() {
    have="$(burrowee-gateway --version 2>/dev/null | awk '{print $2}')"
    if [ -z "$have" ]; then
        info "burrowee-gateway not found — installing from burrowee's public channel"
    elif [ -n "$GATEWAY_FLOOR" ] && semver_lt "$have" "$GATEWAY_FLOOR"; then
        info "burrowee-gateway $have is older than floor $GATEWAY_FLOOR — upgrading"
    else
        ok "burrowee-gateway present ($have) — dependency satisfied"
        return 0
    fi
    if ! command -v curl >/dev/null 2>&1; then
        warn "curl not found — cannot install burrowee-gateway; install it manually:"
        warn "  curl -fsSL https://release.burrowee.com/gateway/install.sh | sh"
        return 0
    fi
    # Threat model for the curl|sh below (accepted, by design): this is the ONE
    # public cross-channel step. We pin transport with --proto '=https' --tlsv1.2
    # (no http downgrade, no SSLv3/TLS1.0/1.1), so the fetch is authenticated to
    # release.burrowee.com by its TLS cert. We deliberately do NOT minisign-verify
    # the fetched bootstrap here: the burrowee bootstrap is its OWN minisign
    # trust-anchor — it verifies the gateway payload it then downloads against
    # burrowee's release key. Re-verifying it from clawee's installer would only
    # duplicate (and couple us to) burrowee's signing keys. We fetch to a var and
    # pipe so a truncated/failed fetch never partially executes.
    bootstrap="$(curl -fsSL --proto '=https' --tlsv1.2 \
        https://release.burrowee.com/gateway/install.sh 2>/dev/null)" || {
        warn "cannot reach release.burrowee.com — skipping burrowee-gateway install"; return 0; }
    printf '%s' "$bootstrap" | sh || warn "burrowee-gateway install reported an error"
}
dep_burrowee_gateway

# =========================================================================
# BOOT UNIT (no sudo): render via `claweed print-boot-unit`, write under THIS
#   user's home, and load it in THIS user's domain. Uses the register socket
#   resolved earlier (explicit env or unique detect). The spawn-helper flag
#   points at the Tier-S path even if Tier S was skipped — the helper is
#   expected to be installed there (now or via the printed block).
# =========================================================================
if [ -z "$REGISTER_SOCKET" ]; then
    warn "could not detect the burrowee-gateway register socket."
    warn "render the boot unit yourself once the gateway is running:"
    warn "  $CLAWEED_BIN print-boot-unit --kind=$KIND --claweed '$CLAWEED_BIN' \\"
    warn "    --data-dir '$DATA_DIR' --spawn-helper '$SPAWN_HELPER' --register-socket <path>"
else
    info "register socket: $REGISTER_SOCKET"
    if [ "$OS" = darwin ]; then
        # The LaunchAgent belongs to THIS user's GUI domain — write it under this
        # user's home and (re)start it as this user (no sudo).
        UNIT_DIR="$HOME/Library/LaunchAgents"
        UNIT_PATH="$UNIT_DIR/$LABEL.plist"
        LOG_PATH="$HOME/Library/Logs/claweed.log"
        mkdir -p "$UNIT_DIR" "$(dirname "$LOG_PATH")"
        domain="gui/$USER_UID"
        manual_hint="launchctl bootstrap $domain '$UNIT_PATH'"

        # Render to a temp; only rewrite the plist when it actually changed
        # (idempotent — a routine version bump leaves the unit identical, so no
        # launchd reload is needed, only a binary restart).
        NEW_UNIT="$(mktemp)"
        "$CLAWEED_BIN" print-boot-unit --kind=launchd \
            --claweed "$CLAWEED_BIN" --data-dir "$DATA_DIR" \
            --spawn-helper "$SPAWN_HELPER" --register-socket "$REGISTER_SOCKET" \
            --log "$LOG_PATH" >"$NEW_UNIT" \
            || { rm -f "$NEW_UNIT"; fail "print-boot-unit failed"; }
        unit_changed=1
        if [ "$FORCE_REPLACE" -eq 0 ] && [ -f "$UNIT_PATH" ] && cmp -s "$NEW_UNIT" "$UNIT_PATH"; then unit_changed=0; fi
        if [ "$unit_changed" -eq 1 ]; then
            cp "$NEW_UNIT" "$UNIT_PATH"; ok "wrote LaunchAgent $UNIT_PATH"
        else
            ok "LaunchAgent unchanged -> $UNIT_PATH (kept)"
        fi
        rm -f "$NEW_UNIT"

        loaded=0
        launchctl print "$domain/$LABEL" >/dev/null 2>&1 && loaded=1
        if [ "$loaded" -eq 1 ] && [ "$NO_RESTART" -eq 1 ]; then
            info "auto-restart off (--no-restart) — restart later: launchctl kickstart -k $domain/$LABEL"
        elif [ "$loaded" -eq 1 ] && [ -n "$UPDATE_MODE" ] && [ "$RESTART_NEEDED" -eq 0 ]; then
            ok "claweed unchanged (binary + boot-unit) — no restart needed"
        elif [ "$loaded" -eq 1 ]; then
            # Already running — likely `claweed update` from inside a session this
            # claweed brokers. Restart on the new binary WITHOUT a prompt via
            # `kickstart -k`: launchd kills + relaunches the job, so it completes
            # even though tearing claweed down kills this very session (no unload —
            # the crash-only KeepAlive stays armed as a backstop). We deliberately
            # do NOT bootout for a changed plist: bootout unloads the job, so if the
            # session dies in the gap before bootstrap, claweed stays down. launchd
            # has no in-place plist reload, so a changed unit (already written to
            # disk) takes effect on the next reload/reboot — the new BINARY runs now
            # regardless. The plist rarely changes; we just flag it.
            launchctl kickstart -k "$domain/$LABEL" 2>/dev/null || true
            ok "claweed restarting on the new build (launchd $domain)"
            [ "$unit_changed" -eq 1 ] && warn "boot-unit changed on disk — it applies on the next reload/reboot, or now via: launchctl bootout '$domain/$LABEL'; launchctl bootstrap '$domain' '$UNIT_PATH'"
        elif confirm "load the LaunchAgent now (launchctl)?"; then
            if launchctl bootstrap "$domain" "$UNIT_PATH" 2>/dev/null; then
                ok "launchd unit loaded ($domain)"
            elif launchctl kickstart -k "$domain/$LABEL" 2>/dev/null; then
                ok "launchd unit already loaded — kickstarted ($domain)"
            else
                warn "could not load the LaunchAgent — load it manually:"
                warn "  $manual_hint"
            fi
        else
            info "skipped load — run later: $manual_hint"
        fi
    else
        # The unit belongs to THIS user's systemd user manager — write it under
        # ~/.config and drive systemctl --user (no sudo).
        UNIT_DIR="$HOME/.config/systemd/user"
        UNIT_PATH="$UNIT_DIR/claweed.service"
        mkdir -p "$UNIT_DIR"
        manual_hint="systemctl --user enable --now claweed.service"

        NEW_UNIT="$(mktemp)"
        "$CLAWEED_BIN" print-boot-unit --kind=systemd \
            --claweed "$CLAWEED_BIN" --data-dir "$DATA_DIR" \
            --spawn-helper "$SPAWN_HELPER" --register-socket "$REGISTER_SOCKET" \
            --user "$USER_NAME" >"$NEW_UNIT" \
            || { rm -f "$NEW_UNIT"; fail "print-boot-unit failed"; }
        unit_changed=1
        if [ "$FORCE_REPLACE" -eq 0 ] && [ -f "$UNIT_PATH" ] && cmp -s "$NEW_UNIT" "$UNIT_PATH"; then unit_changed=0; fi
        if [ "$unit_changed" -eq 1 ]; then
            cp "$NEW_UNIT" "$UNIT_PATH"; systemctl --user daemon-reload 2>/dev/null || true
            ok "wrote systemd user unit $UNIT_PATH"
        else
            ok "systemd user unit unchanged -> $UNIT_PATH (kept)"
        fi
        rm -f "$NEW_UNIT"

        loaded=0
        systemctl --user is-active --quiet claweed.service && loaded=1
        if [ "$loaded" -eq 1 ] && [ "$NO_RESTART" -eq 1 ]; then
            info "auto-restart off (--no-restart) — restart later: systemctl --user restart claweed.service"
        elif [ "$loaded" -eq 1 ] && [ -n "$UPDATE_MODE" ] && [ "$RESTART_NEEDED" -eq 0 ]; then
            ok "claweed unchanged (binary + boot-unit) — no restart needed"
        elif [ "$loaded" -eq 1 ]; then
            # Already running: systemd performs the restart on the new binary, so it
            # completes even when this session is torn down (Restart=on-failure backs it).
            systemctl --user restart claweed.service 2>/dev/null || true
            ok "claweed restarting on the new build (systemd --user, uid $USER_UID)"
        elif confirm "enable + start the systemd user unit now?"; then
            if systemctl --user enable --now claweed.service 2>/dev/null; then
                ok "systemd unit started (user manager, uid $USER_UID)"
            else
                warn "could not start the unit — start it manually:"
                warn "  $manual_hint"
            fi
        else
            info "skipped — run later: $manual_hint"
        fi
    fi
fi

# =========================================================================
# DOCTOR (informational): run the deployment diagnosis with the same paths the
#   boot unit uses. Runs AS THIS USER directly — the whole script is the user,
#   so no `sudo -u` is needed: doctor's checks are user-relative (the allowlist
#   trusts this uid, the LaunchAgent lives in this user's gui/<uid> domain, the
#   setuid helper accepts only this allowlisted caller). `claweed doctor` needs
#   (--register-socket|--socket), so skip when neither is known. Older binaries
#   lack the verb — detect via the usage text so a build without it never errors.
# =========================================================================
if ! "$CLAWEED_BIN" 2>&1 | grep -q 'doctor'; then
    info "claweed doctor not available in this build — skipping (informational)"
elif [ -z "$REGISTER_SOCKET" ]; then
    info "claweed doctor skipped — no register socket known (set CLAWEE_REGISTER_SOCKET)"
else
    printf '\n'
    # Informational only: a ✗ check must not fail the install (|| true).
    "$CLAWEED_BIN" doctor --data-dir "$DATA_DIR" --spawn-helper "$SPAWN_HELPER" \
        --register-socket "$REGISTER_SOCKET" 2>&1 || true
fi

# =========================================================================
# FULL DISK ACCESS (macOS): the pty session runs the operator's shell + commands
#   as this user — BOTH claweed (the broker) and clawee-spawn (the setuid pty
#   launcher) must reach TCC-protected dirs (Desktop / Documents / Downloads / …).
#   macOS grants FDA PER BINARY, and both are ad-hoc-signed (signature changes on
#   every build), so FDA must be (re)granted whenever a NEW binary is laid down.
#   Surface it on macOS: open the FDA pane + name the exact binaries to add. When
#   both were byte-identical, the prior grants still apply — just remind.
# =========================================================================
if [ "$OS" = darwin ]; then
    # clawee-spawn was actually installed this run (had sudo, not skipped).
    SPAWN_INSTALLED=0
    [ "$SPAWN_SKIPPED" -eq 0 ] && SPAWN_INSTALLED=1
    # A re-grant is needed when EITHER binary's signature changed: claweed always
    # (CLAWEED_SAME), clawee-spawn only when it was installed and differed.
    FDA_REGRANT=0
    [ "$CLAWEED_SAME" -eq 0 ] && FDA_REGRANT=1
    [ "$SPAWN_INSTALLED" -eq 1 ] && [ "$SPAWN_SAME" -eq 0 ] && FDA_REGRANT=1
    if [ "$FDA_REGRANT" -eq 0 ]; then
        info "Full Disk Access: claweed + clawee-spawn unchanged — your existing grants still apply."
    else
        printf '\n'
        warn "ACTION REQUIRED — grant Full Disk Access (macOS), required for pty sessions:"
        warn "  the remote shell + the operator's commands run as you and must reach your"
        warn "  files. Add BOTH of these binaries and toggle them ON:"
        warn "    $CLAWEED_BIN   (the broker)"
        if [ "$SPAWN_INSTALLED" -eq 1 ]; then
            warn "    $SPAWN_HELPER   (the setuid pty launcher)"
        else
            warn "    $SPAWN_HELPER   (the setuid pty launcher — once you run the printed Tier-S sudo block to install it)"
        fi
        warn "  in  System Settings ▸ Privacy & Security ▸ Full Disk Access."
        if open "x-apple.systempreferences:com.apple.preference.security?Privacy_AllFiles" 2>/dev/null; then
            warn "  (opened the Full Disk Access pane — click + then ⌘⇧G to paste each path, or drag the binary in;"
            warn "   the claweed folder is hidden, so the + / ⌘⇧G route is easiest — then toggle each ON.)"
        else
            warn "  (open that pane by hand — no GUI to open it from here.)"
        fi
    fi
fi

# =========================================================================
# COMPLETION: non-zero exit if the Tier-S spawn step was skipped, so callers
#   (and the operator) know the install isn't fully done until the printed
#   block runs.
# =========================================================================
if [ "$SPAWN_SKIPPED" -eq 1 ]; then
    printf '\n  ! claweed installed, but the spawn helper is NOT installed — run the printed Tier-S sudo block to finish.\n\n' >&2
    exit 3
fi

printf '\n  \xe2\x9c\x93 claweed install complete (local-source, %s)\n\n' "$VERSION"
